# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6ff40d9f-8ed8-46c7-8bdd-da6242eae75e";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/6ff40d9f-8ed8-46c7-8bdd-da6242eae75e";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6ff40d9f-8ed8-46c7-8bdd-da6242eae75e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix/store" =
    { device = "/dev/disk/by-uuid/6ff40d9f-8ed8-46c7-8bdd-da6242eae75e";
      fsType = "btrfs";
      options = [ "subvol=@nix-store" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9850-7AEE";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 12;
}
