keys:
  - &ataraxia ad382d058c964607b7bbf01b071a8131bf166e80
  - &suomi-vps d286fd9431753cb455537070235ec7bc757002ca
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *ataraxia
      - *suomi-vps
  - path_regex: secrets/suomi-vps/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *ataraxia
      - *suomi-vps
