keys:
  - &ataraxia ad382d058c964607b7bbf01b071a8131bf166e80
  - &nixos-vps 20d2e2b90c6aa179585b6b6b34cafb9db82f1d40
  - &home-hypervisor a32018133c7afbfd05d5b2795f3b89af369520c6
  - &amd-workstation 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *ataraxia
      - *nixos-vps
      - *home-hypervisor
      - *amd-workstation
  - path_regex: secrets/nixos-vps/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *ataraxia
      - *nixos-vps
  - path_regex: secrets/home-hypervisor/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *ataraxia
      - *home-hypervisor
  - path_regex: secrets/amd-workstation/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *ataraxia
      - *amd-workstation
