# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "xhci_pci" "ahci" "nvme" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/95b3583e-41d8-4a34-9ff5-52a7546b9baa";
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress-force=zstd" "noatime" "autodefrag" "ssd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/95b3583e-41d8-4a34-9ff5-52a7546b9baa";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd" "noatime" "autodefrag" "ssd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/95b3583e-41d8-4a34-9ff5-52a7546b9baa";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd" "noatime" "autodefrag" "ssd" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/95b3583e-41d8-4a34-9ff5-52a7546b9baa";
      fsType = "btrfs";
      options = [ "subvol=var" "compress-force=zstd" "noatime" "autodefrag" "ssd" ];
    };

  fileSystems."/media/bittorrent" =
    { device = "/dev/disk/by-uuid/95b3583e-41d8-4a34-9ff5-52a7546b9baa";
      fsType = "btrfs";
      options = [ "subvol=bittorrent" "nodatacow" "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CA29-07D6";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/1bba72d3-9a12-4407-87ab-f2640dbbadf5";
      randomEncryption.enable = true;
    }
  ];

  virtualisation.virtualbox.guest.enable = true;
  networking.hostId = "c4ab8679";
  boot.initrd.supportedFilesystems = [ "btrfs" ];
  boot.supportedFilesystems = [ "btrfs" ];
}
