{
  dns-mapping = [
    { name = "ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "api.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "auth.ataraxiadev.com"; type = "A"; value = "100.64.0.1"; }
    { name = "bathist.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "browser.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "cache.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "cal.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "cocalc.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "code.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "dimension.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "docs.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "element.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "fb.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "file.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "fsync.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "goneb.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "home.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "jackett.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "jellyfin.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "jitsi.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "joplin.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "kavita.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "ldap.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "mail.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "matrix.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "medusa.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "microbin.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "nzbhydra.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "openbooks.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "organizr.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "prowlarr.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "qbit.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "radarr.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "restic.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "shoko.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "sonarr.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "sonarrtv.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "startpage.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "stats.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "tools.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "turn.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "vw.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "webmail.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }
    { name = "wiki.ataraxiadev.com"; type = "A"; value = "100.64.0.3"; }

    { name = "ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "api.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "auth.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::1"; }
    { name = "bathist.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "browser.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "cache.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "cal.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "cocalc.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "code.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "dimension.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "docs.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "element.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "fb.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "file.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "fsync.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "goneb.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "home.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "jackett.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "jellyfin.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "jitsi.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "joplin.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "kavita.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "ldap.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "mail.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "matrix.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "medusa.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "microbin.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "nzbhydra.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "openbooks.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "organizr.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "prowlarr.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "qbit.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "radarr.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "restic.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "shoko.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "sonarr.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "sonarrtv.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "startpage.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "stats.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "tools.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "turn.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "vw.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "webmail.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
    { name = "wiki.ataraxiadev.com"; type = "AAAA"; value = "fd7a:115c:a1e0::3"; }
  ];
}
