# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/50aa73b9-114b-450b-8f87-391bc9d877f1";
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress-force=zstd" "noatime" "autodefrag" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/03696b4c-5edb-43b7-b323-58e01d6c811f";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/50aa73b9-114b-450b-8f87-391bc9d877f1";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/50aa73b9-114b-450b-8f87-391bc9d877f1";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/50aa73b9-114b-450b-8f87-391bc9d877f1";
      fsType = "btrfs";
      options = [ "subvol=var" "compress-force=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/media/bittorrent" =
    { device = "/dev/disk/by-uuid/50aa73b9-114b-450b-8f87-391bc9d877f1";
      fsType = "btrfs";
      options = [
        "subvol=bittorrent" "nodatacow"
        "uid=${toString config.users.users.alukard.uid}"
        "gid=${toString config.users.groups.users.gid}"
      ];
    };

  fileSystems."/media/libvirt" =
    { device = "/dev/disk/by-uuid/50aa73b9-114b-450b-8f87-391bc9d877f1";
      fsType = "btrfs";
      options = [
        "subvol=libvirt" "nodatacow"
        "uid=${toString config.users.users.alukard.uid}"
        "gid=${toString config.users.groups.users.gid}"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F872-88F3";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/0c913e15-8990-44f2-aced-24edc7114f93";
      randomEncryption.enable = true;
    }
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  networking.hostId = "ecd4e08e";
  boot.initrd.supportedFilesystems = [ "btrfs" ];
  boot.supportedFilesystems = [ "btrfs" ];
}
