# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3e19dedb-658b-4173-a8ad-8d733d18f525";
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress-force=zstd" "noatime" "autodefrag" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/46765375-31b6-46a0-8956-1f0e05cf1ff9";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3e19dedb-658b-4173-a8ad-8d733d18f525";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3e19dedb-658b-4173-a8ad-8d733d18f525";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/3e19dedb-658b-4173-a8ad-8d733d18f525";
      fsType = "btrfs";
      options = [ "subvol=var" "compress-force=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/media/bittorrent" =
    { device = "/dev/disk/by-uuid/3e19dedb-658b-4173-a8ad-8d733d18f525";
      fsType = "btrfs";
      options = [
        "subvol=bittorrent" "nodatacow"
        "uid=${toString config.users.users.alukard.uid}"
        "gid=${toString config.users.groups.users.gid}"
      ];
    };

  fileSystems."/media/libvirt" =
    { device = "/dev/disk/by-uuid/3e19dedb-658b-4173-a8ad-8d733d18f525";
      fsType = "btrfs";
      options = [
        "subvol=libvirt" "nodatacow"
        "uid=${toString config.users.users.alukard.uid}"
        "gid=${toString config.users.groups.users.gid}"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E02A-5F90";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/f25cdcc8-c1b3-4014-882e-1a693a15e1f5";
      randomEncryption.enable = true;
    }
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  networking.hostId = "923a7c8b";
  boot.initrd.supportedFilesystems = [ "btrfs" ];
  boot.supportedFilesystems = [ "btrfs" ];
}
