# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/system/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "rpool/system/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/user/home";
      fsType = "zfs";
    };

  fileSystems."/bittorrent" =
    { device = "rpool/local/bittorrent";
      fsType = "zfs";
    };

  fileSystems."/home/alukard/.libvirt" =
    { device = "rpool/local/libvirt";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4F6D-537A";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/3043db40-1d67-47f0-b6d6-d8f1a68b47c6";
      randomEncryption.enable = true;
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  networking.hostId = "d107d6c6";
  boot.zfs.devNodes = "/dev/disk/by-partuuid/8454c73b-e50a-407c-86d7-e970d0fdb09e";
  boot.supportedFilesystems = [ "zfs" ];
  boot.kernelParams = [ "zfs.zfs_arc_max=4294967296" ];
}
