# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/27bedbc3-b6c7-43b1-ba60-792a755ba01f";
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress-force=zstd" "noatime" "autodefrag" "ssd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/27bedbc3-b6c7-43b1-ba60-792a755ba01f";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd" "noatime" "autodefrag" "ssd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/27bedbc3-b6c7-43b1-ba60-792a755ba01f";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd" "noatime" "autodefrag" "ssd" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/27bedbc3-b6c7-43b1-ba60-792a755ba01f";
      fsType = "btrfs";
      options = [ "subvol=var" "compress-force=zstd" "noatime" "autodefrag" "ssd" ];
    };

  fileSystems."/media/bittorrent" =
    { device = "/dev/disk/by-uuid/27bedbc3-b6c7-43b1-ba60-792a755ba01f";
      fsType = "btrfs";
      options = [ "subvol=bittorrent" "nodatacow" "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B0FE-7362";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/bd1405c3-eab1-465e-a83b-0781b430a5bb";
      randomEncryption.enable = true;
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  networking.hostId = "3efba84e";
  boot.initrd.supportedFilesystems = [ "btrfs" ];
  boot.supportedFilesystems = [ "btrfs" ];
}
