name: "Build ISO"
on:
  push:
    branches:
      - master
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'machines/**/autoinstall.nix'
      - 'machines/Flakes-ISO/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install nix
      uses: nixbuild/nix-quick-install-action@v27
      with:
        load_nixConfig: false
        nix_conf: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          substituters = https://cache.nixos.org https://nix-community.cachix.org https://hyprland.cachix.org https://ataraxiadev-foss.cachix.org https://cache.ataraxiadev.com/ataraxiadev
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= ataraxiadev-foss.cachix.org-1:ws/jmPRUF5R8TkirnV1b525lP9F/uTBsz2KraV61058= ataraxiadev:/V5bNjSzHVGx6r2XA2fjkgUYgqoz9VnrAHq45+2FJAs=
          netrc-file = /home/runner/.config/nix/netrc

    - name: Setup attic cache
      run: |
        mkdir -p /home/runner/.config/nix
        echo "machine cache.ataraxiadev.com" > /home/runner/.config/nix/netrc
        echo "password ${{ secrets.ATTIC_TOKEN }}" >> /home/runner/.config/nix/netrc
        nix run github:AtaraxiaSjel/attic#attic -- login dev https://cache.ataraxiadev.com/ ${{ secrets.ATTIC_TOKEN }}

    - name: Build ISO
      run: nix build .#Flakes-ISO

    - name: Push ISO to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nix-flakes.iso.zip
        path: result/iso/*.iso
        if-no-files-found: error
        retention-days: 30