wg-ataraxia: ENC[AES256_GCM,data:DUXlhmTvB5WIJEP7vgr9+YNHlpC0S9Uhcnrp30fvXRehQdGCJvQeOYfHA9ZQ7zl3ZXFHeeM5YbAP0y3eRfvjY27+poW5jzOpj8nv7PB0JKQsF39nYBvWkFg6YpmNYnF6yOWKOK7Ae2cXE4OCWGhGKEtHywv04Mr9b+GgfpFWVxqvanAJ7RFz4nmGf8KK6cKaCyRCeXonEjXh9DfzstIiMYGtBULruw6AZQZP8dRQxoyFQ0/ICIAhiimD5IF/4l8rrdgHYxhn/vZdkhBOfRsH0X19/PiSWdLKAglvCcZK6u0lWEqFMnJFtY77YxXNwEbo5mFN8OVhK0f5T8WGOx5D0dIrkHTaFaOhltMsKwClla5WiYEld5gVuz9TGKoX/W8YANz38fXl2Z2cPShQRN8poHGkTB8iLvVXLx5G3LKMouw01lB+3nrRqZle/THJjFXFhrGla7gGXrKknRq/A/g2CwExiCJIB9num1duTBveQaxSQQ==,iv:h8m/dXC77L6p46rEYIiklZTDUTZgYBg1yiO/klQJGRg=,tag:uEeDkGpaTalFhPT8+R/X7g==,type:str]
wg-dell: ENC[AES256_GCM,data:IUHBtDHFYIhtsO20RGo4Azv2Pc/dbyBvG8F6UJcdtqLRNnl6Q/C/rUZZytsq5tmDeyZ6EJfA8gcEsMcqYdSWhR9lM7cVf/JFGBS4EA82NT+JiV9PzdTahj0eeGEmWsjMsWh74RNkAsOiI3UWIgq3ICuHY4dgWTWmfOz2Fya3uatFwSCgwdCJKJIFIcH/qEdunTL0Rdcj+yykE3OEOGB3ftZFX9cRFhndZhedJKcUdJsBGMauu7w3dFzEbgOd5hUThxaWTWFxStx4DuGNvUtBC1/i/iWM0tpXc0CpnUB6Y0TRW9JKbu0Noo05aQD7neZEK+cJfNLOS7vAu6XRP+hPlqKQQCbvZJRYVhsgVtpNSaIoFtDoL/8kifoyU2JDxWMH1XaqmpWDe3QnpCfh4rAyRRqxP+NdSpBr+Mk5QgTk+zVFhuVFUU38hkbHbIC3uelvYUSNbz7oGOfO1cqBDWlVVJgCg5viiiXodb8NxJVlX/ar32FXq3k52Aajd1NzdFwaWzlUVDEX2OQalf1HpQCdEqRb39NteCtQOii4KCbjod1rT7++H0xProk3L5DyRFeePpjTwbuTqMo0Bg4f5bZ0V484ZoU7Wzho//BrcWw1paKf5rcaVNPZ5grWWCpbrOqc/UVxn0ffi81UpM4c7/rqHj/r60qoWEnvwLWiKFBEd/aJJDZtbp8HH0HS2q7NyXD4X3PHi1CsZoPg3LKbLOxDyUXxihruEhwGe+CYuwFeh2pT7fDhe3AtWw16ThfikjYV/T9PcpHJF4iLupNTKESAbjgges1x2wWVXtqIvPaIe/es9sBEawHKyAJenxoKDu3zLw/efcwQe+PRrzzTlziRjwA8lxl0+Bxf+qx7rrY7eWr4WOjtsbImThJiAagHNRqbtjtCNrm7OsSD4Uob8JlOhpO4F/HSDJDkoncOY/BBVNphOz1xDznJSRLYAavxIcdNnGIBjDIK6pGNFpK1jTqmSVf1W0o2lBnTPrZrbX0nrgAvVJaIdnubrlv/33fAPpvTJF3ymFIVngDBoODXLXcom7OhAEAWAteWQj1V+Xy0xj80QFgWLL6crt2t5qfY6BEbeWvx0mAhFqiwe6sg3CIyQuicdswCRE1Qmq9JPI0MB3Qg92Jbg10rkXx0lXuNptDI9/BrU141NTTuh4FvGF4spqCbpZQd2JAcICauQ2+XBWFwQDdMz57Bqzwc3kPKCCcuf6Yj3ZGt/bcVNV1gsTeyCOzjEVR86a9BL/wOd10niZDh8xfkqEjZ3r8U56+9dlaKrQ3tx2bOX3AAWL0S1D/j9flY5tNX3WaJz/b6aPE3UcK92IcfJzhbYr7pm+NwndSQqdoCcl1QnLPOCcEjnPbkWaw6lORu8LBFnnmGEBPBfikth6uMUW91ZVR8A5qU8xSplUqAVN+cDil5RjyTanrL3tMw+8AHHa/ifYViQJyrxZ7+iEOYrsRf8AFgqVnaDlWfM15knjPYozgjR6C+JqRdDgqHVkZwrrbPSVoCOq2Yf98mR5qVUFwi9BTQOnebPG+H0Yr3jYkdRB7AuN2BKYhvc9NDsznI9rXkQdSTliCmZgPO/TyCGUN8vXvjlXcyh8uIix+vYbhf4yWBIagCf+OvaoOO3NHs0YADNm37dun8x8UHKUcmRXDLvz68oRFNG+SSbPsKZNplCO8Jg2oSwkghrgIfvhfAv8eqNBQ7bGkYqIXVz2PCenVRpXVIYN2TQPt+LjRqaNVfNujeNPDGBBSQ0FM1NmdAHy1dMtuVEZzX2Rmxn5dRO0IK7NwogNIgVC7Jw/mCT+CT9SHhZKpJaHdGOv4O513rFG29Qeyoi6szP5dNNrhOUHGTJZHFLqBtAlTneevR2vnoenVzmr8+xkvJq0wd5UHxoMlNKnF5ex416D2kBpiYBLZP47FUDkfbsYlx+vQbaeiEgT/V4Q4YmZ5h67AoidLISKaFg2dWyeJ2gmmUFON+mPiJmJzoDLCOZimi7GdNk4pjX2qY29pAm7jQdF7j3ZpgyGt/nElRrIEEhek813M2bt25murpEEbgoJf5tR44qgpbdTycdz/G3YLIQ3sgY0RdEm9lkolCO7Pqh4TxSw4WzbSiMUg49cs4z0b62mCBQSr5smTNv0N4+QAsJ8PnCZEgVm0buU12SLtY6Ty7/RWB8Gqb0I5SHUzOvkGEuME4FG9yMiJ7UT+NhdV8Pq4C3TgFeSqDnH0qIkjOgZng4Rl1TEfZvnLq1bjsQIAPl4nfD3RY2+VV,iv:RhPtay1IjAq40plSm5xVzUGbdkCcLwCVsOVysChDGag=,tag:ML99P2YlxsNIdmcxu6hbKw==,type:str]
wg-hypervisor-dns: ENC[AES256_GCM,data:bqiFalZaSx1Xguhufa656uHfyfcCdeXJdtcsWeaGMwBJwO7JXAnFw2eB8y2H4Xr1nrwwravnp3hPmEcLI8eIWUCU+IhNDF0ghkU+YtBcb5HWNRLV9lqqs9dGwEcX9SXQ12lTci0uJxo0nMWcNQWTSALjx7GLHQLmSbmRrGFl5Fxc+NjuAnEH6bQflOVQhjqaUwgYYTOnxdIF6ljDg2+28pfM7RixxKsJc9E7iO9JHYzzwL2Q63w103fIlfroBQ0t6S7gqqB5ahXB/gnr4Cgq4gMFdLdL7LCKPEmpT442wvLt4yjNytdC3P+jxjOK4AHpFHQUps+MH8eapkIrTUhnveITi0dgxOVyAIls+wDYphHEYxXUkkSw+BlCvbygSfHfwj9Lxksn7k1E9D0EN68yNtFpR+72Bfl6H/7BOw==,iv:3GcVUj9EzogzQ78ImEkBfT1Ula28i3dKH2be5Q3ignA=,tag:9+54I6P/JKtmqW5RyOLTLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-21T16:36:51Z"
    mac: ENC[AES256_GCM,data:AmoEIOX4ROFpg60hymSw24oWXs/SodzEvodq7YkUkbeD30woka625KmEwTbpLH6vqaODJU8NS5ioHaFg+ErFY84B+FDz885UYOjeNK0Z/dm4AqjBi3YDxKmfedwpIfzpDO+hDHGOP3/EBALO2Se87Q9hu6NwED+nSRqLqlpPE9w=,iv:tzt2hNr28mSDhTwKBuPVIMhGiD0/KlE/oSx8HICH+Is=,tag:qh29t54uCGxt8flcj43cPw==,type:str]
    pgp:
        - created_at: "2024-07-17T08:44:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwcagTG/Fm6AAQf9F+zA2wfti/0Z/XCuHVBIUUYikcxeQO9CQdmc6rRwdtoR
            WgYd3nYmPF7g6a215vAO+PNV5alkAByVYnEpUpr87TUGYOgXwQfJQp3xGIHV6gDG
            8LnVViiFokMy5vgpJ2MYnyjQDH8Aahz0y7SpEoWrm3VQ1/55Gw72Hnmz4u+e0lXA
            IJ41rIrNL+RB7bLjGuPVENaf2/VTb4EjbhjOfEPHSGuvkdaF5xg73Ho8yzvO5vOy
            u8pJf+WqIrLudhWRWHJgVZQFJcYMD2lLfGDZD6uSLB39tbGG5g8m70iD0AfB5r4V
            kV1zZBraM7STgzkgQroXH8HAGtbXbECOXcSIjwzQMNJYARzj2xJRBaoZzPsSBQmA
            V2nhFtkDRFRhEhXxqKZxwwi5np7SBlN0EasS+PUhUQZ0cNkOT5t/def4LT9o46hi
            TDO/lH2wvwCkE0YomYkJfz/yB+VTqVmsTQ==
            =iPjS
            -----END PGP MESSAGE-----
          fp: ad382d058c964607b7bbf01b071a8131bf166e80
        - created_at: "2024-07-17T08:44:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7DEqu/04FqmAQ/+JGRz8AoIEJgjnESe7GJ/O1B70k79N4EeUMORiF/xVjxb
            Wjj4Fp3qrQyIYfvVmVzzn+PurQIQ5Wnogl1nk8cixq3yVBR/9/0saqmsFqSJai/D
            iMDY5QpBBDQGDH11GtTBbEEGXC+5TjCCEDKFJ55Bho5QCdEqS2hnCzO+tNl0eY8H
            e3Xkmshk42Jjbt2DeHRzsxqGmZYzwaSFBVNWONvAqqHaCv8TLSwctaxuazZXNIeS
            2ERJNE+d9w0AJBP5l/hEtTkLnYKpqU1FLqh5wWlgEbn0wZ4UUK4CSiEYvxtT/jbZ
            iybpMql4/Vj9FA+HbLU2nPK8yxLA6QDcm8DpNyLEl5l5BDmaJUPq/JO9wPlfpBrd
            Tv83nO7Fb/GoXWaGkGVPrRGPL0JLpcKWpC0GsC6pLfkYZH6ztIihob5WB41lg+aY
            JvXdbzEE5NJO0cbw3GSDxHIiSffLpsXTIAx1Y/acfoqsCCU9XCimnJPulZyy3UbT
            oKr8LaLvDG3W0XM2A5fEKBoxEZ/PKjvNHn68/klzrz18H0KIz6IMgA4lequmL1lO
            pj57QuPqjwzLuESP004UDlVZzXm8G7LCSYqVZmZuRxI1ErJlsxultK/G2S2j4fu2
            Oqq4hinozUFm5qyYEGkaGeRXW5dyrO+eECsFQEI6qlb9BmFc5NcAdzVWqcP9JT3S
            WAGPsHYMeYYFJ0swI18sVW6Nsrw4InnuhlsYA780VCWARJeEQzNkpENC9BG2fqKl
            VVp1u0sw8ykYgYFaUbqGfu8IzyW0dVqXgAWeelQE0aJA7ZMe7+hBAfY=
            =6XgJ
            -----END PGP MESSAGE-----
          fp: 4ec141b4dd5a00e108b36211b0c4aaeff4e05aa6
        - created_at: "2024-07-17T08:44:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA187ia82lSDGAQ//YSp/2vDLkGDio5iZDUH6ymUbO0v9uBUuVqVjBURd73ZH
            2S/6te73K0rCe0sIbH5JPowvHqf+tbUOnelcf2h5Bi3HRfPvbeCHluyRAHvbTX44
            3GLHdq8zLBF1/m3puY2zaKGc6uBEGi7UGfdYlE0ntNLNQ14Lo4A9rJOBJ0GOCj6+
            kRoqmBocECoB3hqZPVV4+pawqmH3RM8SO9c8UmCwfYXE2rVhHJdgoKhhJBuRXHKC
            fZBuKrWUhqZXIXZyyI2bcdMQIzzmheXZA1YOtza3rdpNQ3JTqKXA4xxCI8lomrs3
            JdQeWTX82aMp0JQD7ZFHXf6vHuoTBBRBDpzfE3NgAGFylOawCj+AK64brrr+BiC/
            bn7SlXpdrkDziyDt2bXHprwuCW3tvmGrqxBdtxbmXRxlcJNd9duyQTOn1DJ3kfHU
            T9tRBY+54GSRdSuWAmhddKgizO2mY4ErbF7UptLzW4E3PIKxYw2mALUDKSnRDmkC
            Dse/eltuDLGXZZhX9Ggphr7QY1z7qIpczvTbf0H/5fNk2D/EiLLk+Wp2VOudrSwB
            +A3oP/sVI9eWuRIGtPDriD0cJKxrGfVIrXKhNs9OR6QXAnlDt7IPVBTGlVe4PTjb
            9uebaX6fg1UehEMWp7ObzA4fIdIuFQo6971LG61sWaM8pUycBUKHXdJTmSb/xr3S
            WAHrzwANmqWu1zpEd2VRvefnhlCmObfjhbzn2+kW+TowiJMJlp5azPMoCXCqL9QW
            KrgCHXUmOS9H2EIvKvFerU2gHeRfZv8urxhfjfu9jiojDwszc8tSfuY=
            =jvfW
            -----END PGP MESSAGE-----
          fp: a32018133c7afbfd05d5b2795f3b89af369520c6
        - created_at: "2024-07-17T08:44:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4NImSg+4iqHARAAgCp3sslIvhk1EuSK+dsmMzI6X8wO8/RoE9tisyXxvXkH
            oQYuPOS+e9LB6O/vMCQhCwULXN16rXDIzbVsb4r/OULLSdyCwbrh1OJ74IkiVQ9e
            u61f+IdVkgpppTohMU8uj0sJl/w7L20mBXnlsP7LZRRx9YHjIKIqwjuxuStPoPX0
            ioSYBlJBs4YwvGWv6VHbs+7sgRrb7PaAatHjSQ1KynGZA38YlDxsLF0JKpMQloUY
            IJvRL7vlqBnp7uGGLSZqVgLL5Oq5ZSzHqscDmzLxT10aNJQG4GAy768YIHyNaKz8
            ht+ftR3odzK0l6/e3WomHseSS4kyVYMMfEU21k+nWeN7dXdesEYeAuPu3pxpgnr5
            YBDP3tvxJziCnkxx3cL7cGbb+gw7cKaFbw8445U/lA+q848IoVQtAGD8TMfHZYbU
            wcayQIEVdUETRqhRd7N61lqvO21tqjseGtYeeq5VaaIzYam71OrtXqQA/ngmkp76
            2jIPjTbK3FiaCcEgbvsXSk6NakD6Glx7+0QzlPVSe5rzjB8zzjlidlEOTWnN6p0P
            0BZzznJLWTZlHaPAkNfxuCQ0mQ3ak5LBvNEyqv20ceIXhYfX26HeUuuoAptwMqr5
            gb3z44diQHg1F9GF4T/2WzmiIEpjpYZkaMDHiKpAnafUoQ97qBj3pl0nuX9tilHS
            WAF80cyIUat0H39G86GTggEmL8WKt/+J2WZkoHKiqs/AoJnjjpkiE998Vjn8WIbk
            WLRxl/fRVQeY0+ieDWkf7BHbyhoIjRB4yQ/F8fJa02nODUBsEgPo0Bs=
            =aKrr
            -----END PGP MESSAGE-----
          fp: 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
        - created_at: "2024-07-17T08:44:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9T+KNkhS2haAQ//QchRcXQvupplzucutlGLgMR+7kmp1F4/3rMnhRQcJS03
            EeXlbnBKUa78i77lthdDA+ZFTfswF0Rv7M3QZ8qRBC1lQKEh0yImLI+ulG9ljEP3
            fly9c7vkgJ5hSOLe7rw6eDF3wl3Mme9f/y1pXspVYShE5B3WqGfnxZLHQFvNp/7+
            0UoaiEATN/Fqw1x8+jAZ7pKAE+cICHvEc89UzgV8K1maZkPd9HafV32r7T8yZNLh
            88Dk6HtVMe50EOLBBEoK1sYvvee95ZkrmNHCI7jNf2XDnr9zygLFloCiMk1pXqat
            VvY8tW2VO5nnFjaB8q862vvrlEbpN3ACmNmnsi6xvkoPlc27zjL3dkh5tgH9CxL+
            LmtPcCUMQAh3IeTr7tmEKFWrYpRyioyOYjKDpJ5pqsBGXZvbX8X+XiMHY6kC9vdg
            MjUX2nUG/Ssu4TcDzZ0IVmjvVFP8mWSufKok1/pYhjpNrlsGRX7ZbIMFx6BZhvin
            lINDZI/xBvJi0IfVDMxvEXmjZLY0Vi787dvWIbLhN0nPDEIm7tyRTGtpzHygh1le
            ZM5qsoY3U7TkBYnbTqY8Z4m3w/Qet2SHTdGqFDgTMCGay7ZWahBXFnfBEn+Or//u
            0SudWrWAAEapAUtZKBAnSdczmMRKbtU8TIm5tgHlFol62CsjYy2NC0kyyUqMFFPS
            WAG5Xma6wjZj6A5vgFN6AxALu8gDq7tzozD06GyoBmJC6y6b5wA2fNq5pk2iICd8
            d0VRL0dCGxTdR75iksRMbBYLjGcRKmrvDNNtP/rOlqw3/fyh8oqgkks=
            =ZYZB
            -----END PGP MESSAGE-----
          fp: 05588f4245256f75a8da42e5d4fe28d9214b685a
    unencrypted_suffix: _unencrypted
    version: 3.8.1
