wg-ataraxia: ENC[AES256_GCM,data:DUXlhmTvB5WIJEP7vgr9+YNHlpC0S9Uhcnrp30fvXRehQdGCJvQeOYfHA9ZQ7zl3ZXFHeeM5YbAP0y3eRfvjY27+poW5jzOpj8nv7PB0JKQsF39nYBvWkFg6YpmNYnF6yOWKOK7Ae2cXE4OCWGhGKEtHywv04Mr9b+GgfpFWVxqvanAJ7RFz4nmGf8KK6cKaCyRCeXonEjXh9DfzstIiMYGtBULruw6AZQZP8dRQxoyFQ0/ICIAhiimD5IF/4l8rrdgHYxhn/vZdkhBOfRsH0X19/PiSWdLKAglvCcZK6u0lWEqFMnJFtY77YxXNwEbo5mFN8OVhK0f5T8WGOx5D0dIrkHTaFaOhltMsKwClla5WiYEld5gVuz9TGKoX/W8YANz38fXl2Z2cPShQRN8poHGkTB8iLvVXLx5G3LKMouw01lB+3nrRqZle/THJjFXFhrGla7gGXrKknRq/A/g2CwExiCJIB9num1duTBveQaxSQQ==,iv:h8m/dXC77L6p46rEYIiklZTDUTZgYBg1yiO/klQJGRg=,tag:uEeDkGpaTalFhPT8+R/X7g==,type:str]
wg-dell: ENC[AES256_GCM,data:IUHBtDHFYIhtsO20RGo4Azv2Pc/dbyBvG8F6UJcdtqLRNnl6Q/C/rUZZytsq5tmDeyZ6EJfA8gcEsMcqYdSWhR9lM7cVf/JFGBS4EA82NT+JiV9PzdTahj0eeGEmWsjMsWh74RNkAsOiI3UWIgq3ICuHY4dgWTWmfOz2Fya3uatFwSCgwdCJKJIFIcH/qEdunTL0Rdcj+yykE3OEOGB3ftZFX9cRFhndZhedJKcUdJsBGMauu7w3dFzEbgOd5hUThxaWTWFxStx4DuGNvUtBC1/i/iWM0tpXc0CpnUB6Y0TRW9JKbu0Noo05aQD7neZEK+cJfNLOS7vAu6XRP+hPlqKQQCbvZJRYVhsgVtpNSaIoFtDoL/8kifoyU2JDxWMH1XaqmpWDe3QnpCfh4rAyRRqxP+NdSpBr+Mk5QgTk+zVFhuVFUU38hkbHbIC3uelvYUSNbz7oGOfO1cqBDWlVVJgCg5viiiXodb8NxJVlX/ar32FXq3k52Aajd1NzdFwaWzlUVDEX2OQalf1HpQCdEqRb39NteCtQOii4KCbjod1rT7++H0xProk3L5DyRFeePpjTwbuTqMo0Bg4f5bZ0V484ZoU7Wzho//BrcWw1paKf5rcaVNPZ5grWWCpbrOqc/UVxn0ffi81UpM4c7/rqHj/r60qoWEnvwLWiKFBEd/aJJDZtbp8HH0HS2q7NyXD4X3PHi1CsZoPg3LKbLOxDyUXxihruEhwGe+CYuwFeh2pT7fDhe3AtWw16ThfikjYV/T9PcpHJF4iLupNTKESAbjgges1x2wWVXtqIvPaIe/es9sBEawHKyAJenxoKDu3zLw/efcwQe+PRrzzTlziRjwA8lxl0+Bxf+qx7rrY7eWr4WOjtsbImThJiAagHNRqbtjtCNrm7OsSD4Uob8JlOhpO4F/HSDJDkoncOY/BBVNphOz1xDznJSRLYAavxIcdNnGIBjDIK6pGNFpK1jTqmSVf1W0o2lBnTPrZrbX0nrgAvVJaIdnubrlv/33fAPpvTJF3ymFIVngDBoODXLXcom7OhAEAWAteWQj1V+Xy0xj80QFgWLL6crt2t5qfY6BEbeWvx0mAhFqiwe6sg3CIyQuicdswCRE1Qmq9JPI0MB3Qg92Jbg10rkXx0lXuNptDI9/BrU141NTTuh4FvGF4spqCbpZQd2JAcICauQ2+XBWFwQDdMz57Bqzwc3kPKCCcuf6Yj3ZGt/bcVNV1gsTeyCOzjEVR86a9BL/wOd10niZDh8xfkqEjZ3r8U56+9dlaKrQ3tx2bOX3AAWL0S1D/j9flY5tNX3WaJz/b6aPE3UcK92IcfJzhbYr7pm+NwndSQqdoCcl1QnLPOCcEjnPbkWaw6lORu8LBFnnmGEBPBfikth6uMUW91ZVR8A5qU8xSplUqAVN+cDil5RjyTanrL3tMw+8AHHa/ifYViQJyrxZ7+iEOYrsRf8AFgqVnaDlWfM15knjPYozgjR6C+JqRdDgqHVkZwrrbPSVoCOq2Yf98mR5qVUFwi9BTQOnebPG+H0Yr3jYkdRB7AuN2BKYhvc9NDsznI9rXkQdSTliCmZgPO/TyCGUN8vXvjlXcyh8uIix+vYbhf4yWBIagCf+OvaoOO3NHs0YADNm37dun8x8UHKUcmRXDLvz68oRFNG+SSbPsKZNplCO8Jg2oSwkghrgIfvhfAv8eqNBQ7bGkYqIXVz2PCenVRpXVIYN2TQPt+LjRqaNVfNujeNPDGBBSQ0FM1NmdAHy1dMtuVEZzX2Rmxn5dRO0IK7NwogNIgVC7Jw/mCT+CT9SHhZKpJaHdGOv4O513rFG29Qeyoi6szP5dNNrhOUHGTJZHFLqBtAlTneevR2vnoenVzmr8+xkvJq0wd5UHxoMlNKnF5ex416D2kBpiYBLZP47FUDkfbsYlx+vQbaeiEgT/V4Q4YmZ5h67AoidLISKaFg2dWyeJ2gmmUFON+mPiJmJzoDLCOZimi7GdNk4pjX2qY29pAm7jQdF7j3ZpgyGt/nElRrIEEhek813M2bt25murpEEbgoJf5tR44qgpbdTycdz/G3YLIQ3sgY0RdEm9lkolCO7Pqh4TxSw4WzbSiMUg49cs4z0b62mCBQSr5smTNv0N4+QAsJ8PnCZEgVm0buU12SLtY6Ty7/RWB8Gqb0I5SHUzOvkGEuME4FG9yMiJ7UT+NhdV8Pq4C3TgFeSqDnH0qIkjOgZng4Rl1TEfZvnLq1bjsQIAPl4nfD3RY2+VV,iv:RhPtay1IjAq40plSm5xVzUGbdkCcLwCVsOVysChDGag=,tag:ML99P2YlxsNIdmcxu6hbKw==,type:str]
wg-hypervisor-dns: ENC[AES256_GCM,data:bqiFalZaSx1Xguhufa656uHfyfcCdeXJdtcsWeaGMwBJwO7JXAnFw2eB8y2H4Xr1nrwwravnp3hPmEcLI8eIWUCU+IhNDF0ghkU+YtBcb5HWNRLV9lqqs9dGwEcX9SXQ12lTci0uJxo0nMWcNQWTSALjx7GLHQLmSbmRrGFl5Fxc+NjuAnEH6bQflOVQhjqaUwgYYTOnxdIF6ljDg2+28pfM7RixxKsJc9E7iO9JHYzzwL2Q63w103fIlfroBQ0t6S7gqqB5ahXB/gnr4Cgq4gMFdLdL7LCKPEmpT442wvLt4yjNytdC3P+jxjOK4AHpFHQUps+MH8eapkIrTUhnveITi0dgxOVyAIls+wDYphHEYxXUkkSw+BlCvbygSfHfwj9Lxksn7k1E9D0EN68yNtFpR+72Bfl6H/7BOw==,iv:3GcVUj9EzogzQ78ImEkBfT1Ula28i3dKH2be5Q3ignA=,tag:9+54I6P/JKtmqW5RyOLTLw==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n0prg9vynuwc56gn0xfe5qde8wqcd4uzg5ghhhetu2024ckvjyvqxf49el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaVptcjdRbzRpSkRwSG43
            SEV6MmJ2SVY4TDhiSUVlSitEdTdabVhqWm1rClNjWFd3bHcwUFdOeVVPSTg4bUx3
            am9zQUc1SFZuMmV0cGVyWnpwM2ZBZmMKLS0tIGNrdnh6QkZzWVIrekdtak4yMjdw
            MEVxaVZ2R3VoaGdNSWR1WkhSZ1BKQjgKHO8lCIBxuvxq/ebahF+2nd9BDcf1vgir
            mo5Ul32kpy/3iHa39ah3R1Nvcvgefl2lsJE2n8DnWO4JKU9uMo1ZnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ztrteyc2hae7c0tlrjx9pcjjtyeqazsq7ztf7dcmxlyxg5x2mcwq75p65f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK1FVUFArUWZxY2I5cklh
            Q1IySTd5aDBMK2FhRVcyeW1WdE0zcFUza2xjCmhpT3BMb0VmM2toQm56d2hwYjFk
            aGxDWHlNd2p1RHdMcS83Y3oxLzI1NXMKLS0tIERGNXc0UG5HYXkzM2ZUWUpXT1lW
            K2xWYzhkbDM1K00vbnVDaXhLdDRpd0kKEeLEa/9gLUJag8CZcDJxaCd8QsVq5pCg
            ydom2Yuju5oI10mANIYOeKQHJ4SKFulHMGDrgBUAi5+c/ZXSqYHNJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T16:36:51Z"
    mac: ENC[AES256_GCM,data:AmoEIOX4ROFpg60hymSw24oWXs/SodzEvodq7YkUkbeD30woka625KmEwTbpLH6vqaODJU8NS5ioHaFg+ErFY84B+FDz885UYOjeNK0Z/dm4AqjBi3YDxKmfedwpIfzpDO+hDHGOP3/EBALO2Se87Q9hu6NwED+nSRqLqlpPE9w=,iv:tzt2hNr28mSDhTwKBuPVIMhGiD0/KlE/oSx8HICH+Is=,tag:qh29t54uCGxt8flcj43cPw==,type:str]
    pgp:
        - created_at: "2024-10-30T22:53:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwcagTG/Fm6AAQf+PozhAte0wpyf6gQ3VKRxQghWfjw4cEtT9/sH76kbh9nl
            y6odG7tyChff2V/YCuWsSFdNcHJZ4OLHMvAAlEj9ehHkkC5jOULiFKEEkt55sb/i
            A79ozLGzKmdHEeZMZmYtjDfugtAFf/UkpLp9FntEK2KoOEmagkCwbDtjgV/7TZil
            zY9JrvUFbRduIcS+bHwihX4M1ztm3jnjlMIE84fvTyAOAae078emYruPp8vYUeLX
            bUzp8onceUPnVy3Yzh7yO+3w1/YZMtUxYDk32C8H9IsjUs+RyRtBWgt3GsfRRzn+
            JRGhiR/jKj/uN2zLgzGgt68oDb531opr/vwP++ehdNJYATArMBpohI37gREOR9NI
            mz8NAnk5GdsJjTsQ5ryokkhM7E97Y6zO7h5Oy3ombhwcZ1K87OAyQMpAnYI408tM
            3tu0qzl6tVrvGYbLG2d1hoDi0yMvr4c6NQ==
            =l5UO
            -----END PGP MESSAGE-----
          fp: ad382d058c964607b7bbf01b071a8131bf166e80
        - created_at: "2024-10-30T22:53:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7DEqu/04FqmARAAnZHqvcfBPFqpKG1vNrAZRbgeQJNwqN/zXqr8ecBCHKVu
            EC1eiUImxmPJG9zLk2pd5nYVTElkD2dwS3rO3bkYVIGBU1UD4n95VQ/WSdY8n/JT
            +AxMvAxa/XabEngAkRVIgGlTGMCndas7L4/GSIH6D/+eDMxTK/l3wmLYBrwYNzSh
            7oiIlTauVnKMfbEbpKNO4yQRz70SHE3FbzkcskUCVrkmmCB23YnwBhaAeh5268KW
            tflCbYumRnWXn0j2IzaLvVoXpayfCTljTw2YMZ/L1c3pzq4lKNAKW8ThSHpkWvil
            INAUIREb60aw41WVnYtKorxBAkYEZ9gLH+vwQtsPXK4FYnP0x81AiWwwiWizbBNj
            ioOvpRGmpGBn0CYAYeuWo3U5ktShHFuASQhFqeg1G9g5nlqxeO9mOBOj9lbkiRHF
            oskEZShDjuBybvVAowFLidWjAOIj8uurWKt5xpbutIIRNpcMKAjBAL+DVOBZ0ND/
            2OWSB+dagRApU+dvuJ7IjXNPwYn6faPhpRhBGJK00XdM88VwVldrEs9MMlelLR5I
            xLBn9ebOp1/BeY+ZVUjt2yLYZr4iyMJ7BGdVW95SwQSt3D2WeTE8eyrFWI62PSB5
            uPpzZiQyN/rsC0WxHAxyfVUA4M+ndeAadBZUfIP1ZEt2Kd6yF/HVpA3kmRQwTZbS
            WAF8jitS0cdXzwrwI6B/+V8sOo5xRTxlpxPeq8D5xkxSGZfYh3x8g844Q9O2hpwu
            kIcLt1s4PLmuNthjba6rJTnNPxdjA2WrfRkn2sEZdDvg1JKXd4uvNyc=
            =jp3h
            -----END PGP MESSAGE-----
          fp: 4ec141b4dd5a00e108b36211b0c4aaeff4e05aa6
        - created_at: "2024-10-30T22:53:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA187ia82lSDGARAAg4GZ8GimjyXyUUaj1tFDdcox1ao3DYAcPw0KeBjt95Wu
            VIi3Or8qs8+4IanOREyURknBl0c1PgnxAqdcf0/iqTuhXoy1FkWWrB+yh1k3ZI2D
            WEvOnzHDghTjbnq52eG+khudSe35gtXAN7iMJQr8DJFvreJK+FQ48Q48h62v/h47
            n8v3ShoLGIcmoqO4gdlLNDAlkKV1WSgYAQ1iqRL8OK5c0wx76q7eF2ZkzUjv7Hfq
            qbeBley8Woc70axQZeqz1lmbHWxl/Sbmvb2cXmSORkaSs/OF6I0jicxFugQJP5qm
            rfNoEEa/SIe+x5Iqn6kFODxTpqJviLdoSGPauHU3E9HEK7tfNARV7wXV8PcwP+jL
            m425qjQu9TdIX5UYKp1PIWdxkKZyOOdAiY8DrWQxLQHb4Voa4hxk+ziokd0egCTK
            GyyBm6dDS9Yd+51sX4AMApYUirSxVoX+ZUu8/n6ceukDJ5ZP4Ufpj4JbQr27elBl
            w5ieOObUy7qnMF9rtB0h0iiWuf5ovPUwVq7VIKBoer4zvuf1hM6COcE/9t9cqtLV
            wd4NDDl2xocsvoltp0KBxklk1kqa5B7ps0n2+/tk8SC8Rt5PdGlU5vwPCfZc/ycv
            V1+pA1N7EwFnJ34R9n2JUaVnlV1yCVphhNWXO6Rzf/U9A8fN6fOZN1y+YNCsjo3S
            WAFjEnpVMVfjUMNauYNCjrt08okOcfm9oxvAdbc6ghVTbOF0cCf0z22zpQk7ZcxF
            MEnpCV6usfvdXmfUlptJvDvDIvFUPgKvOFaweYrl1I3H1pkUd6Ile5M=
            =Aif8
            -----END PGP MESSAGE-----
          fp: a32018133c7afbfd05d5b2795f3b89af369520c6
        - created_at: "2024-10-30T22:53:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4NImSg+4iqHARAA1lAt88SoOLKK6VGQsu4Z/vj3nxcc6wdUiiJ2YRBZ7KaQ
            1Kmi5EzLq6pNYH/GOxfo9P8hO+Y9LoZGwitzYT8K+v240S1QYzOCLUu/CPv4Uw+1
            KnBgMyv0bDiDJhUpjEWILStA5pxx2+QiEktPVjaVf3YIH0NQkkEOYOeI++bm0eU9
            MTcKGTBUEJEJbm6d4l6tyDhoxp/TDGhadIGIT/cHPjwTrKMjdK3F0vCP2YQOZ/4r
            CuB93B9xP0J6Q6DkC4TjpDXp/JsiD9XahUsT9l97rRZfI87bfOWDcpaQaIZAiZ0Y
            Xhmw+tISqfARcHV1JjARqJsjnG0dCvidpNHmNjBzqBl67OQpouUAOaU6awN5dwtP
            5ISRYLtGihDcvpsdzk1+HJSTwh5Kb5xn4NrLnLhhEeqjDQk9PISOVYB4uNs2g/cm
            MdQBqO709GnbhACnYOHyunYxcI//VvuSKl8p5AbGQOY174DL/2Np03vkK09g6P/J
            QLSBJfuZOZCf/mest5tnftk/5DgV49mDFd/OGdCQu9dJZ2FTYRsOMrUa8UwL9SE+
            u5YheyJlsWn6ngEuScCOuJG9kPT6DZyO0gE2NGX+FUlHDVaev4BX8mZs6QFTpnI4
            PPsQXuh4nJxdc2w7gUXMTe3U7wW0aZ5iEMvdgIf7wjVc5P1OPEFEi6QIgai0FmnS
            WAGuqpVYZV/hVf47LVsvD4C54JZSSF11PxtoWqO1iXV0ZNlXGv+sX+oh4A//ddLf
            PG22GxZC5TSVbbn5CbAfap8WirB6vQL0enCoi4MHqihgM+boIpPv6tU=
            =Xzu9
            -----END PGP MESSAGE-----
          fp: 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
        - created_at: "2024-10-30T22:53:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9T+KNkhS2haAQ//RNOjZ4s7izgGc5MPdG4GV26O/wTh6QK4dyYgqmBJkZO2
            9EfkTNCGOHm0Z2eFnFYmQvmTtdGlXflg2DJj+hwmqZ1HQ5zSqte30wgpELGXldRB
            CLuqd0VPr5SkmS8smcuYEtKk16NH/3/Zs+HQKwwNKsE/hD3NeMYxggE5OL6VgaOh
            0r1JQ4VtIgjt5OP657a99tithtDrwdIOnkhJ+Luh7jh29hnwvw3YORUb2UnUwPJA
            poFEmTcUNjoZ8VUSHwpdie5U23SdmQzUS0UWXkh9BTM8fIJWnhiPkCuYB0fzrs2v
            u2OE68ny9LIxEMf3gV4OcqaHR5ORz3z2szlH3d3GV3Ms+O4egzuYbKia2MwQ9dCR
            xDtBCmGsedM4dglN8u3QxgUYwcRenc7bX8N/wk8MO0XtXP1fYKZO/xhslGy28avH
            XCkT0lFvy3lLsJViCj3na+VWw5vwoSzHVlGxPTsHOiX94CoKqIvc/PbPMG+rxaY7
            s9eZdn9/aqUhwRRK8yuKHaivnInx1c6OJhGPxb4Rv5zvCstoAz7yakTWSfctY9XG
            gOjTR0BA/d32H8HglnFy2pj4elpc8CnRSxriAOCUwFmuu7NiQeML5j6LBY4IrFnB
            2jIS7YfzdV8k+VdB7KDEfXLj59d4lppDG6ihC/mtwQCKlDmTGv4xLktDCcVLfizS
            WAHbDPrP8sDoN0h/cThPYM37DSy/mMxEK66dZXu0VvUmoKDJY/f5mqPlN/2g8vZe
            GTroJVqyRsyqAUmI0gZPL7SPED9SeVUXxg+gwqizdmuS2mloSl1nCsw=
            =5L2e
            -----END PGP MESSAGE-----
          fp: 05588f4245256f75a8da42e5d4fe28d9214b685a
    unencrypted_suffix: _unencrypted
    version: 3.8.1
