wg-ataraxia: ENC[AES256_GCM,data:DUXlhmTvB5WIJEP7vgr9+YNHlpC0S9Uhcnrp30fvXRehQdGCJvQeOYfHA9ZQ7zl3ZXFHeeM5YbAP0y3eRfvjY27+poW5jzOpj8nv7PB0JKQsF39nYBvWkFg6YpmNYnF6yOWKOK7Ae2cXE4OCWGhGKEtHywv04Mr9b+GgfpFWVxqvanAJ7RFz4nmGf8KK6cKaCyRCeXonEjXh9DfzstIiMYGtBULruw6AZQZP8dRQxoyFQ0/ICIAhiimD5IF/4l8rrdgHYxhn/vZdkhBOfRsH0X19/PiSWdLKAglvCcZK6u0lWEqFMnJFtY77YxXNwEbo5mFN8OVhK0f5T8WGOx5D0dIrkHTaFaOhltMsKwClla5WiYEld5gVuz9TGKoX/W8YANz38fXl2Z2cPShQRN8poHGkTB8iLvVXLx5G3LKMouw01lB+3nrRqZle/THJjFXFhrGla7gGXrKknRq/A/g2CwExiCJIB9num1duTBveQaxSQQ==,iv:h8m/dXC77L6p46rEYIiklZTDUTZgYBg1yiO/klQJGRg=,tag:uEeDkGpaTalFhPT8+R/X7g==,type:str]
wg-dell: ENC[AES256_GCM,data:IUHBtDHFYIhtsO20RGo4Azv2Pc/dbyBvG8F6UJcdtqLRNnl6Q/C/rUZZytsq5tmDeyZ6EJfA8gcEsMcqYdSWhR9lM7cVf/JFGBS4EA82NT+JiV9PzdTahj0eeGEmWsjMsWh74RNkAsOiI3UWIgq3ICuHY4dgWTWmfOz2Fya3uatFwSCgwdCJKJIFIcH/qEdunTL0Rdcj+yykE3OEOGB3ftZFX9cRFhndZhedJKcUdJsBGMauu7w3dFzEbgOd5hUThxaWTWFxStx4DuGNvUtBC1/i/iWM0tpXc0CpnUB6Y0TRW9JKbu0Noo05aQD7neZEK+cJfNLOS7vAu6XRP+hPlqKQQCbvZJRYVhsgVtpNSaIoFtDoL/8kifoyU2JDxWMH1XaqmpWDe3QnpCfh4rAyRRqxP+NdSpBr+Mk5QgTk+zVFhuVFUU38hkbHbIC3uelvYUSNbz7oGOfO1cqBDWlVVJgCg5viiiXodb8NxJVlX/ar32FXq3k52Aajd1NzdFwaWzlUVDEX2OQalf1HpQCdEqRb39NteCtQOii4KCbjod1rT7++H0xProk3L5DyRFeePpjTwbuTqMo0Bg4f5bZ0V484ZoU7Wzho//BrcWw1paKf5rcaVNPZ5grWWCpbrOqc/UVxn0ffi81UpM4c7/rqHj/r60qoWEnvwLWiKFBEd/aJJDZtbp8HH0HS2q7NyXD4X3PHi1CsZoPg3LKbLOxDyUXxihruEhwGe+CYuwFeh2pT7fDhe3AtWw16ThfikjYV/T9PcpHJF4iLupNTKESAbjgges1x2wWVXtqIvPaIe/es9sBEawHKyAJenxoKDu3zLw/efcwQe+PRrzzTlziRjwA8lxl0+Bxf+qx7rrY7eWr4WOjtsbImThJiAagHNRqbtjtCNrm7OsSD4Uob8JlOhpO4F/HSDJDkoncOY/BBVNphOz1xDznJSRLYAavxIcdNnGIBjDIK6pGNFpK1jTqmSVf1W0o2lBnTPrZrbX0nrgAvVJaIdnubrlv/33fAPpvTJF3ymFIVngDBoODXLXcom7OhAEAWAteWQj1V+Xy0xj80QFgWLL6crt2t5qfY6BEbeWvx0mAhFqiwe6sg3CIyQuicdswCRE1Qmq9JPI0MB3Qg92Jbg10rkXx0lXuNptDI9/BrU141NTTuh4FvGF4spqCbpZQd2JAcICauQ2+XBWFwQDdMz57Bqzwc3kPKCCcuf6Yj3ZGt/bcVNV1gsTeyCOzjEVR86a9BL/wOd10niZDh8xfkqEjZ3r8U56+9dlaKrQ3tx2bOX3AAWL0S1D/j9flY5tNX3WaJz/b6aPE3UcK92IcfJzhbYr7pm+NwndSQqdoCcl1QnLPOCcEjnPbkWaw6lORu8LBFnnmGEBPBfikth6uMUW91ZVR8A5qU8xSplUqAVN+cDil5RjyTanrL3tMw+8AHHa/ifYViQJyrxZ7+iEOYrsRf8AFgqVnaDlWfM15knjPYozgjR6C+JqRdDgqHVkZwrrbPSVoCOq2Yf98mR5qVUFwi9BTQOnebPG+H0Yr3jYkdRB7AuN2BKYhvc9NDsznI9rXkQdSTliCmZgPO/TyCGUN8vXvjlXcyh8uIix+vYbhf4yWBIagCf+OvaoOO3NHs0YADNm37dun8x8UHKUcmRXDLvz68oRFNG+SSbPsKZNplCO8Jg2oSwkghrgIfvhfAv8eqNBQ7bGkYqIXVz2PCenVRpXVIYN2TQPt+LjRqaNVfNujeNPDGBBSQ0FM1NmdAHy1dMtuVEZzX2Rmxn5dRO0IK7NwogNIgVC7Jw/mCT+CT9SHhZKpJaHdGOv4O513rFG29Qeyoi6szP5dNNrhOUHGTJZHFLqBtAlTneevR2vnoenVzmr8+xkvJq0wd5UHxoMlNKnF5ex416D2kBpiYBLZP47FUDkfbsYlx+vQbaeiEgT/V4Q4YmZ5h67AoidLISKaFg2dWyeJ2gmmUFON+mPiJmJzoDLCOZimi7GdNk4pjX2qY29pAm7jQdF7j3ZpgyGt/nElRrIEEhek813M2bt25murpEEbgoJf5tR44qgpbdTycdz/G3YLIQ3sgY0RdEm9lkolCO7Pqh4TxSw4WzbSiMUg49cs4z0b62mCBQSr5smTNv0N4+QAsJ8PnCZEgVm0buU12SLtY6Ty7/RWB8Gqb0I5SHUzOvkGEuME4FG9yMiJ7UT+NhdV8Pq4C3TgFeSqDnH0qIkjOgZng4Rl1TEfZvnLq1bjsQIAPl4nfD3RY2+VV,iv:RhPtay1IjAq40plSm5xVzUGbdkCcLwCVsOVysChDGag=,tag:ML99P2YlxsNIdmcxu6hbKw==,type:str]
wg-hypervisor-dns: ENC[AES256_GCM,data:bqiFalZaSx1Xguhufa656uHfyfcCdeXJdtcsWeaGMwBJwO7JXAnFw2eB8y2H4Xr1nrwwravnp3hPmEcLI8eIWUCU+IhNDF0ghkU+YtBcb5HWNRLV9lqqs9dGwEcX9SXQ12lTci0uJxo0nMWcNQWTSALjx7GLHQLmSbmRrGFl5Fxc+NjuAnEH6bQflOVQhjqaUwgYYTOnxdIF6ljDg2+28pfM7RixxKsJc9E7iO9JHYzzwL2Q63w103fIlfroBQ0t6S7gqqB5ahXB/gnr4Cgq4gMFdLdL7LCKPEmpT442wvLt4yjNytdC3P+jxjOK4AHpFHQUps+MH8eapkIrTUhnveITi0dgxOVyAIls+wDYphHEYxXUkkSw+BlCvbygSfHfwj9Lxksn7k1E9D0EN68yNtFpR+72Bfl6H/7BOw==,iv:3GcVUj9EzogzQ78ImEkBfT1Ula28i3dKH2be5Q3ignA=,tag:9+54I6P/JKtmqW5RyOLTLw==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n0prg9vynuwc56gn0xfe5qde8wqcd4uzg5ghhhetu2024ckvjyvqxf49el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYU93T2N1YkpjV2dIZUli
            M2FhZUtJL3A1R3g3eExxU2lpMWRiWnIvc1dnClM2bDRWTms5bWxsR1Y2Zk9GVk9L
            YldpcGkxMVYvY0VhMW51aElvQ1hUNWsKLS0tIHNuY0JDTmtyZmVaelZ3dE0xcUVw
            UWZrMXJsRG5BU1pUZDY3NllZUytIVncKS2rf1qD1mOKNdQSiHhrNFvZPGr5haOBe
            8eD4a8FlH9aSxgIHp+emgYxcqCxdXLjwQ+TDzjsSoEX+1RvOlk/l/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ztrteyc2hae7c0tlrjx9pcjjtyeqazsq7ztf7dcmxlyxg5x2mcwq75p65f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z0J1QW9OOEoxT1JkNXNZ
            RUNMQWUrODZpcnZYYXdjOU1yN3pqd3NBNGpRCko3S3Jtd2pLeXlFRVpaWElCekVt
            T2RYRHVuUDRpZWtCVmRlWnF4WkZlaDQKLS0tIFBRWWhwUHpCT2g1VE5qVmFjaTRp
            eGhuTDBRM1BpUXRFenhTVkszRkQzQncKacBHoQ290K3gIkgC69x8C/UPPpG5dFk1
            lqRE8sFYr6MTrhcjgCtBic2vCTO9YQAhP19FuqW8nRFkqlZBUz3v2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m5msm7rgqye2q9zesgedg0emga4ntehlr629786lrxs3rhk0squq0ly9je
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZzdIWm1vZ1dyWTUrSmRh
            Y0NWUkJJZnRPYUxBVEdnZDIxd296aDFsMXdrCk5PWUxHNGRuVWJoWUt3VzJkdlFu
            MVl6QUIwTTRpMWVEM2cySWhlTnUwLzgKLS0tIEtGZVFNelhITEdRV2VBOGdDaWJL
            b29QanBoNUpnM1BRbWhqc0phMkhEbzgK/Fq6BBhJZpqkKg5H96Xpzwow9a+mbUtw
            1bzfTKd7xsRm5vHruRmAzElFnmF8X/8XoQoyAj5Rn5KOFCW1+FoOaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T16:36:51Z"
    mac: ENC[AES256_GCM,data:AmoEIOX4ROFpg60hymSw24oWXs/SodzEvodq7YkUkbeD30woka625KmEwTbpLH6vqaODJU8NS5ioHaFg+ErFY84B+FDz885UYOjeNK0Z/dm4AqjBi3YDxKmfedwpIfzpDO+hDHGOP3/EBALO2Se87Q9hu6NwED+nSRqLqlpPE9w=,iv:tzt2hNr28mSDhTwKBuPVIMhGiD0/KlE/oSx8HICH+Is=,tag:qh29t54uCGxt8flcj43cPw==,type:str]
    pgp:
        - created_at: "2024-11-14T20:08:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwcagTG/Fm6AAQf/f7EgNcKhRjSSXBwxWWweVfR11JrKsSLspOzYKyyGPXVA
            zfm4eOStGxdB+dOuzoJd6x/4BLFkvtM/Jy9yx2En6k5520e69XCIh0kvEpd8i1iJ
            RL3aB73uRoMtCaU9Eq+XjlBniuwtHxjbxBYimczQbbMAdkTVkYPlokhfLzfT2JUy
            /U1/NXZkLXHGWgoNLraf3CMxv+gbCoSj0cc8+RzdlXXDUUUwDGYnPekaB+fzrEu2
            VVOTYhIQXrnLL2ANtfFPQy0Mp7yl4Iu+K2urQ8t0WDlTVwqruda1Vz3ULokMHZNo
            Un9SsPdIkt2G5u7ftv5AKHnC0IE82JMig3dx0buaD9JYAYL2ovc9wPsKQHr+347Q
            eeZRuaEaRhc76sCsmwjlUaI5Hq18Ya+dkWvOkaYrrLbh4Ps/8SEW0Ms56Y06EAug
            N8LdglQo4iqeUIqykSvkFybqgeU3h1aXgg==
            =R17y
            -----END PGP MESSAGE-----
          fp: ad382d058c964607b7bbf01b071a8131bf166e80
        - created_at: "2024-11-14T20:08:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7DEqu/04FqmAQ//TXu8rJ9IPZMhHvKyXk2Q8cRSbj0Fn6DZg6Xjk4hVrGP8
            zRpB3FFvyCGKFllxHaCC83fJKxHRkFCJ1JoLxOB5V4J/Ety4AVXmEgJHkosI0QOz
            Ip3db7zYIpgU8rOylAYLvX2KoxrxfytG82mfetPEbzoBZZOyBMVU2Z04QGxNH3aH
            E/yS8k91vPZumh6bfEQiy3aEoAkC/o15bJ50xVElmKRM8Er1/jTGECiqFdRIxoEB
            N2P8YlswbfVBFMS68LCQ1fXdFWXOTpvrdGKsGzSpeUodyq5ESxMM1EBCISuQHOIX
            IbzZPoyTZZvZAcn0wOhdKjVFWzFty89TdK7N36SZkhMYbjgLLPbSJRuWBMdbquhY
            oX3ddQ4bqYv60pa789t/m8dPXTo0tKa/DElo5ckNziqJzGxAxAwCcrKH949D0h3k
            ngr0Lz3PM5Quo8T2Y3N+0MwQ9TfFczADMmg6Gnw/pG+1hpV1yo3RZvCAujltKFA0
            TUINf/KnqzKCBcrT8ioEtFznl6uo2C3yS37EHSfh7ctYRvPL4ykeFcHxhelUwqV1
            2hva+PK2o3c+L5VFghkR6jokKGQDydKRV5mSu2uTnpmrZ9m4Opbxw9x1sBCyR4na
            V5tVkGdiSScdUmwieMQ7L7flhFLbXHxaL2olvj6gnFktqWRfSQ2jhTuF/C/GcU7S
            WAEHvJlxIpVRa+hoshJn5jezLMWQPbOST+VqSm1Kc8cERXsVzeyhlk59Z+zzYqDt
            D10okSQ0oojicNYMXq9FgPnfpzI4o0DA1Ilalzvr/tPE6kwkInE2hQ0=
            =hj0/
            -----END PGP MESSAGE-----
          fp: 4ec141b4dd5a00e108b36211b0c4aaeff4e05aa6
        - created_at: "2024-11-14T20:08:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA187ia82lSDGARAAwAqyjO96GcYYO0AtyTJQHGTMj2IhYhMx82oWDk3lWra6
            026cpcBlJns8Lrg5kMe6Kf9PMMH10h5Rs1Q4QPJofTYwqVbjXWtsCWNAdBH64KgG
            VxDNmAESc5tqUEo/njmH6+v6H3rTdDH6eBteDIhL+/V1a4wTAIJmX7YMjtcuoJRn
            QGUGTDtlDCiIQ3NWt6KZjm+eao7R7IOlyg65KHF/Mpcek2BbEf/RCi0XBncdtk3G
            /McMc+4M47v+0LL9Lsc/T/viFw7Lc89UZszNP2irBm6m30Axmt1C+qXjGXqhdfP6
            hl1UpYNo+Ara8RfjClO4CNH31KIpB9MFAnqkK+6CBfGn5Us4+C4P7B2p01q01pEq
            K4Xe7IrGDUSZ0O5RIGY3LsQtUhiirZaFsQ5xQJE3F4mChcjxpTN4Nl50cJ8rHgMS
            Rxp9gjIJyAY79lvMGLpTxW4XXUlJ635KdA4GLoq59JGMta/Ue5Lq3pVtdFViHPrf
            UmEUhRfpCXFofx2mrjXUsuF5hjJUolAOintwnhFiPJjbiKkxcU9oRcQRgnLjCUhV
            dWtqKBp2Rlau32jRjOcRUDzBxp+M6t2NYoB/wZS7cQxMHPO4DEIGY6ALSTcz6O/f
            qfiF3ss0znuW2dfqZKfxedM/T/fkilPjOMg0x4RDAYX4LIYsPoN4Q931w4FJ71zS
            WAFUP9C2kgTL+RHpB63/MIOMrBempI9m1hLL+Prtp8ZcPOLjqAqiUT3DyX3R5zkQ
            b2lgMpP1cmN3hySC9ej3aIQSlSUdllvYJCTZFaDvn3MNA2G7GL96pTY=
            =GvjO
            -----END PGP MESSAGE-----
          fp: a32018133c7afbfd05d5b2795f3b89af369520c6
        - created_at: "2024-11-14T20:08:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4NImSg+4iqHAQ/9EcDETlYQ+qyTS8c8lG01/h3uAN5cIERCdnYAbMtQ4HLR
            /BW/c1z8kmb6qHvi7qyBou5ur3X7Bq3DgAQS7bhUyYUocGXzfhWMRPuF711mmJZ4
            eI6HhilRbTI9yXCQhfInLe/fTISimieca64+SQAbfBuxiMCsZfKYEcEvXBhl7+Gn
            swqSLHw/fXVpRS5CvhRMytuaRaR1ineKMZRnPZnQXZIQ5ioFH25smLMKke9B+oqb
            94Wj8F9CFeYoyhEFV6N62cxYpJ7Fg4KrEb2CvGNpvOUKWjKpWqYCkWrThOjAQpXu
            kVWgbptN86OvX3nKDZWh5Kwf/XFVn/k4rCiOD7gw2KQgn7b4sbvCiSf+jBCD6wWK
            yZ4oiAzBShUBsGJ1Q9i7PlyN73h7jMcBRm5BU4fJE+wGofAGbIFATN7FXO5+Hfw4
            1nIekJ3ESw8Do3mUUDpakf+1jSdw3wJs04iP0/ZtJ4PqR9dBRmTsaJt9QZDlyM8Y
            FCL+zsO9rgUUevGTkVvlZFQYp5fMb0vrxBMtTFw8JeI6RXEr6Gcx+f9PJA0J09z6
            1rJ7Pu6/Wa2xfGpNaMuDJU2o1UdWS0QL0kIFWLIFNphH8K1K8D/rt6oQET+uPCnJ
            hJqPoKG3LMgye1FI+FAAph1/p8k1YxxfbSwTEAnQ3z494gVBHCeaJPwF7HHVDCzS
            WAE7d0oUbcaUeMdNZTfdMqguYfboJkqf0JdvcDF/wZm/BOji3+57xZ9ZiKUW1TRK
            R2UHfuSFC8Hguw7+Kk3smfMczUKw4dU5RJd5RJnDPwcENpkxmo95Rtw=
            =wYy9
            -----END PGP MESSAGE-----
          fp: 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
        - created_at: "2024-11-14T20:08:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9T+KNkhS2haAQ//XmroctkanKolrmGvaCXuhORkG5zXMTNo2HM9FIEFkPQ+
            cNSZPm9YnVMUfeZzksr7iih4LpMKTPLSRt5fbXucChJY6H/eq7k1asjUc51SDhJY
            YyENpxnSKUs0oYeGq3FXX9apmPVPE0hnIdM+kKRnoSxN+YZngARxKvQB8OkLo2sb
            WBe2IzwgrlDnIn0QVmHfmA+h9pezmMqk/j2fX7YfbrXKnizS+naYQV1jFS8DO/iC
            PN5Ik4xwzbsQDEpQnGECF3EvOShwNO3kTHn1XJ/7psfXt9tRMUfQ3BZTnk0xHyI7
            ORqOoPag6F4HBAtXiyFx9QirGQ2EhDT/KOrLbaIN+IfQ7BiyZKqvud1tGuMDnDJg
            Rc05OINhIJdxZvs6t8vL1Z1tU9sTqNI7CGk7IRiD91wwb5+tRSVCGaMs+JS3KsUJ
            Q6wimpE66Xx5lN3XubPkXQ0TmPMdrb79yknSoXcCvY9voD2IdvYAGR/eK7GQAZLU
            t1SqRjBfO/cbK9SvKbNpfGm/O0JV5FsAo8QC2/2VHt2a9wIb2Oi2tTl15Xq6lmDA
            kNU2mc0PTCq3A0AdZd9A9KFpQRcU2tBZtxlXdm+OH6vXfSytVphZnEHEZQ2Q0sAJ
            NXIYrEP90dpEGkZnPIR9DAVKUvGy0R4JZF54JYQR2EQ38q5OCuiBAMugJVDatcrS
            WAG/IexWnflIlD+bPBt5qVsCMuBPSzTSTqdTZgC8mdfGo6wPqKHvcG3M7K9f2biU
            56H67mamQxUlXulAGD6Jh3EUCeCjqAdRIEnt9Xcbk055OYoMPIaguPA=
            =4JQz
            -----END PGP MESSAGE-----
          fp: 05588f4245256f75a8da42e5d4fe28d9214b685a
    unencrypted_suffix: _unencrypted
    version: 3.8.1
