wg-ataraxia: ENC[AES256_GCM,data:DUXlhmTvB5WIJEP7vgr9+YNHlpC0S9Uhcnrp30fvXRehQdGCJvQeOYfHA9ZQ7zl3ZXFHeeM5YbAP0y3eRfvjY27+poW5jzOpj8nv7PB0JKQsF39nYBvWkFg6YpmNYnF6yOWKOK7Ae2cXE4OCWGhGKEtHywv04Mr9b+GgfpFWVxqvanAJ7RFz4nmGf8KK6cKaCyRCeXonEjXh9DfzstIiMYGtBULruw6AZQZP8dRQxoyFQ0/ICIAhiimD5IF/4l8rrdgHYxhn/vZdkhBOfRsH0X19/PiSWdLKAglvCcZK6u0lWEqFMnJFtY77YxXNwEbo5mFN8OVhK0f5T8WGOx5D0dIrkHTaFaOhltMsKwClla5WiYEld5gVuz9TGKoX/W8YANz38fXl2Z2cPShQRN8poHGkTB8iLvVXLx5G3LKMouw01lB+3nrRqZle/THJjFXFhrGla7gGXrKknRq/A/g2CwExiCJIB9num1duTBveQaxSQQ==,iv:h8m/dXC77L6p46rEYIiklZTDUTZgYBg1yiO/klQJGRg=,tag:uEeDkGpaTalFhPT8+R/X7g==,type:str]
wg-dell: ENC[AES256_GCM,data:IUHBtDHFYIhtsO20RGo4Azv2Pc/dbyBvG8F6UJcdtqLRNnl6Q/C/rUZZytsq5tmDeyZ6EJfA8gcEsMcqYdSWhR9lM7cVf/JFGBS4EA82NT+JiV9PzdTahj0eeGEmWsjMsWh74RNkAsOiI3UWIgq3ICuHY4dgWTWmfOz2Fya3uatFwSCgwdCJKJIFIcH/qEdunTL0Rdcj+yykE3OEOGB3ftZFX9cRFhndZhedJKcUdJsBGMauu7w3dFzEbgOd5hUThxaWTWFxStx4DuGNvUtBC1/i/iWM0tpXc0CpnUB6Y0TRW9JKbu0Noo05aQD7neZEK+cJfNLOS7vAu6XRP+hPlqKQQCbvZJRYVhsgVtpNSaIoFtDoL/8kifoyU2JDxWMH1XaqmpWDe3QnpCfh4rAyRRqxP+NdSpBr+Mk5QgTk+zVFhuVFUU38hkbHbIC3uelvYUSNbz7oGOfO1cqBDWlVVJgCg5viiiXodb8NxJVlX/ar32FXq3k52Aajd1NzdFwaWzlUVDEX2OQalf1HpQCdEqRb39NteCtQOii4KCbjod1rT7++H0xProk3L5DyRFeePpjTwbuTqMo0Bg4f5bZ0V484ZoU7Wzho//BrcWw1paKf5rcaVNPZ5grWWCpbrOqc/UVxn0ffi81UpM4c7/rqHj/r60qoWEnvwLWiKFBEd/aJJDZtbp8HH0HS2q7NyXD4X3PHi1CsZoPg3LKbLOxDyUXxihruEhwGe+CYuwFeh2pT7fDhe3AtWw16ThfikjYV/T9PcpHJF4iLupNTKESAbjgges1x2wWVXtqIvPaIe/es9sBEawHKyAJenxoKDu3zLw/efcwQe+PRrzzTlziRjwA8lxl0+Bxf+qx7rrY7eWr4WOjtsbImThJiAagHNRqbtjtCNrm7OsSD4Uob8JlOhpO4F/HSDJDkoncOY/BBVNphOz1xDznJSRLYAavxIcdNnGIBjDIK6pGNFpK1jTqmSVf1W0o2lBnTPrZrbX0nrgAvVJaIdnubrlv/33fAPpvTJF3ymFIVngDBoODXLXcom7OhAEAWAteWQj1V+Xy0xj80QFgWLL6crt2t5qfY6BEbeWvx0mAhFqiwe6sg3CIyQuicdswCRE1Qmq9JPI0MB3Qg92Jbg10rkXx0lXuNptDI9/BrU141NTTuh4FvGF4spqCbpZQd2JAcICauQ2+XBWFwQDdMz57Bqzwc3kPKCCcuf6Yj3ZGt/bcVNV1gsTeyCOzjEVR86a9BL/wOd10niZDh8xfkqEjZ3r8U56+9dlaKrQ3tx2bOX3AAWL0S1D/j9flY5tNX3WaJz/b6aPE3UcK92IcfJzhbYr7pm+NwndSQqdoCcl1QnLPOCcEjnPbkWaw6lORu8LBFnnmGEBPBfikth6uMUW91ZVR8A5qU8xSplUqAVN+cDil5RjyTanrL3tMw+8AHHa/ifYViQJyrxZ7+iEOYrsRf8AFgqVnaDlWfM15knjPYozgjR6C+JqRdDgqHVkZwrrbPSVoCOq2Yf98mR5qVUFwi9BTQOnebPG+H0Yr3jYkdRB7AuN2BKYhvc9NDsznI9rXkQdSTliCmZgPO/TyCGUN8vXvjlXcyh8uIix+vYbhf4yWBIagCf+OvaoOO3NHs0YADNm37dun8x8UHKUcmRXDLvz68oRFNG+SSbPsKZNplCO8Jg2oSwkghrgIfvhfAv8eqNBQ7bGkYqIXVz2PCenVRpXVIYN2TQPt+LjRqaNVfNujeNPDGBBSQ0FM1NmdAHy1dMtuVEZzX2Rmxn5dRO0IK7NwogNIgVC7Jw/mCT+CT9SHhZKpJaHdGOv4O513rFG29Qeyoi6szP5dNNrhOUHGTJZHFLqBtAlTneevR2vnoenVzmr8+xkvJq0wd5UHxoMlNKnF5ex416D2kBpiYBLZP47FUDkfbsYlx+vQbaeiEgT/V4Q4YmZ5h67AoidLISKaFg2dWyeJ2gmmUFON+mPiJmJzoDLCOZimi7GdNk4pjX2qY29pAm7jQdF7j3ZpgyGt/nElRrIEEhek813M2bt25murpEEbgoJf5tR44qgpbdTycdz/G3YLIQ3sgY0RdEm9lkolCO7Pqh4TxSw4WzbSiMUg49cs4z0b62mCBQSr5smTNv0N4+QAsJ8PnCZEgVm0buU12SLtY6Ty7/RWB8Gqb0I5SHUzOvkGEuME4FG9yMiJ7UT+NhdV8Pq4C3TgFeSqDnH0qIkjOgZng4Rl1TEfZvnLq1bjsQIAPl4nfD3RY2+VV,iv:RhPtay1IjAq40plSm5xVzUGbdkCcLwCVsOVysChDGag=,tag:ML99P2YlxsNIdmcxu6hbKw==,type:str]
wg-hypervisor-dns: ENC[AES256_GCM,data:bqiFalZaSx1Xguhufa656uHfyfcCdeXJdtcsWeaGMwBJwO7JXAnFw2eB8y2H4Xr1nrwwravnp3hPmEcLI8eIWUCU+IhNDF0ghkU+YtBcb5HWNRLV9lqqs9dGwEcX9SXQ12lTci0uJxo0nMWcNQWTSALjx7GLHQLmSbmRrGFl5Fxc+NjuAnEH6bQflOVQhjqaUwgYYTOnxdIF6ljDg2+28pfM7RixxKsJc9E7iO9JHYzzwL2Q63w103fIlfroBQ0t6S7gqqB5ahXB/gnr4Cgq4gMFdLdL7LCKPEmpT442wvLt4yjNytdC3P+jxjOK4AHpFHQUps+MH8eapkIrTUhnveITi0dgxOVyAIls+wDYphHEYxXUkkSw+BlCvbygSfHfwj9Lxksn7k1E9D0EN68yNtFpR+72Bfl6H/7BOw==,iv:3GcVUj9EzogzQ78ImEkBfT1Ula28i3dKH2be5Q3ignA=,tag:9+54I6P/JKtmqW5RyOLTLw==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n0prg9vynuwc56gn0xfe5qde8wqcd4uzg5ghhhetu2024ckvjyvqxf49el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRE1oWWtPRHNEWmR1aTJJ
            VnNoU2hkL3FWUWJDRWNQOC9XQ3luQ0JlQmdNCnd3d29TWElQL0F5WGdmUkI1TUZu
            eDVueXhsbzZ1ZTVNaU5uQllieXBTQUUKLS0tIGplYzF4QTl2UGJkTkZYU2ZSbVVU
            YWpMbEVVQk11T0tUc0trbCtDU0w5MFEK/n31D8cNPDVhTNFslZfZ8VtvsAqdKT4v
            bnDtrdb7K7WtnBx1YoswHK+WmAKbpIjZ7mewG+FW8PpB7MvjxHQgpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ztrteyc2hae7c0tlrjx9pcjjtyeqazsq7ztf7dcmxlyxg5x2mcwq75p65f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S0lYOUZQdExQZFdSY0sx
            UmtlYmExTkpuRjFxdjdqQlhnUElKaVdoemdFCitYRTEvUWloZzhXNHhhd3BMdWk2
            K1pvOVhtMDR2NGZGQjVFMGJEclh0YVUKLS0tIExnRUNwUHltVWlIUVUyeCtvS2FF
            SEpKK25XN21kQ3A4dlhSb0VMRFc0d1kK5X1rbxu7g++IeP+pQWUN+/bb55G943pw
            Unng6A15yKEEx1mB+sZilyWLNddtFxwOuwx1Mjtv1esC+HKwAQ+oHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m5msm7rgqye2q9zesgedg0emga4ntehlr629786lrxs3rhk0squq0ly9je
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSUZOWHdlUVBCNUJscEp3
            M2tPVGN4eGwrNmcxZ2JsQzlPQ3k1TnhGWHpzCmxrbEgyejg4ZW5tY0dIc09WcFMx
            T0gwSGJtQUU4Y1g2VzlQbmRyRG5Sd0EKLS0tIDBkTkFVS2NWclQ2aEIxSUtyOUMw
            VUtOdXlqd3JEUEpoWHUzNzAyR0RDREkKDtEWfc0ndtJCgnDSwu5b5KgkXX8N+XRc
            oEK30PTHWznmyn4QIOPbaV+L/HyffJbex7BIg7jZ+k87k1Fri5rPJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xxakyntj60nds474xyhpqtl2cvyktefrqcd79x5ava6amewzugmq60rcdh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OFQycjY4TWQ1Vzh5czZa
            SXRwVC84MGhLSE5RQUxtNXduNjZJYmxoWVhnCkJqUUUwWjB4R2xEa3RqY2YvVEtF
            Y2FqbTFxOHAzSUpjeWZkTFdvdi9tdlUKLS0tIGswRkNhUkRaN3A2Z3JDUE5ZNkZx
            SUZUM2xkQTZ6WmpnZUJ4UmQrOTB6eGsK2V1duEpF25cjAs8mKjif1tG8Neg2eMhz
            vjhMsbvhNduxr7+BwB5RHaVec3GH/c4GlOjxmDzFePohS8HeZ/04BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T16:36:51Z"
    mac: ENC[AES256_GCM,data:AmoEIOX4ROFpg60hymSw24oWXs/SodzEvodq7YkUkbeD30woka625KmEwTbpLH6vqaODJU8NS5ioHaFg+ErFY84B+FDz885UYOjeNK0Z/dm4AqjBi3YDxKmfedwpIfzpDO+hDHGOP3/EBALO2Se87Q9hu6NwED+nSRqLqlpPE9w=,iv:tzt2hNr28mSDhTwKBuPVIMhGiD0/KlE/oSx8HICH+Is=,tag:qh29t54uCGxt8flcj43cPw==,type:str]
    pgp:
        - created_at: "2024-11-29T19:58:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwcagTG/Fm6AAQf8DzajfMufhOHRDj9j4th4lYGILRGFMroaYFOfBMoLXsHG
            gchQmsjrZ+aoMGDpWQh1WjL8vkeHIM4flnkzsRdbrtIgOY5Z1w2GnBQ+6tk8vsew
            7N6SCVrOFi39YtpAA55j+8ykUycNl4vjMIwvQoUbLqTvOZ8Chv8ysuTBVkYo368x
            CDrqXCG4V+yUX1NZIxARcH3BRx/QL7wU3Y8w5rWZ824cjN/1hZKb0fpKYKT/EfOq
            GD5vRf4sr7W3l+AYcAx9rH2Q6gjxZRinloOMjtN6utcF8bSDeMDz+Ev6aEZ9tmqo
            dOF6Wc34hEk3SSI+KLZmopfSqlJ6XH2pPp8msUhlnNJYAdexAaN+H7Uy7ZxZJK/v
            +xdfvoWkDYNrDkQelI9n944dS95zC8C6nG63f6Z2/hhwnnqVKPhR8gwqexG/FJH+
            ZUehy9yrFh5LEngjkv3J5PITvz5Tuen03A==
            =By8s
            -----END PGP MESSAGE-----
          fp: ad382d058c964607b7bbf01b071a8131bf166e80
        - created_at: "2024-11-29T19:58:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7DEqu/04FqmARAAmt/KgKd/hWPDyXBBuA8nEELPAsf3YL1a6UoCVVVBM2nP
            tYD06rlvhnmPequIGbGIdRKrAsufyrccT0UZ9QVibfnIP+6Stc8Yx9qGkxV/Ka9n
            sRDYQfzi/kBaTaWO5Jdfx7MbN4ZDrjTEJKqamQFBLmDe+Xlkyz2ZLmMPOsN1vhCy
            FZptkN/k5gCOtscPLtwO9S04nklyjMjqCUKqJ+5NIx4GZhJPkPGCK3CIk12Yvuwa
            5hxRGaPq8z4zF8O/ttJ1c/QsG2MsakeoDgqtygagMRX1qC+Vpz7nS7Cl+jANo4b7
            ft71mu9S+17m+5Ycyu07Zmc1ZONcMAt6Tk1HO3mw6/kyupv+Xn4eSCRFPJMtUig6
            pOiHHpuoCHNbHdXfdz/EuGf1NMRRDE+Ku+jsW18KOIzLeIZXocEOdOdulsjcM+Fs
            zKqRMQZy/Sljm68BWh0Tv31nDmpVo9INPFrI+7ca8Mzo72T7NRH6vsp8RAyhCRI0
            pAIaOcAbgLqU8Q8l6X6Sr5PAhWv94yBCE4w8WNTRMDY0QICDk7jZe2nezrWxEBWC
            HPJOnznufXRw54kXtunXl0qWHuFn3De2Q8YUichhdIGZQDFL+0SdYnCZWdMVnOQR
            /PrEYtX8w+Y+GeVsQ22uZ7pyu0RHec9aiTXzCrop1AvZ6f9Ayc5JLtbCw//Uok/S
            WAHQcTTQW/uLCqJymSNRGttgSlPZLpnsCTaJR4LFQPhq7zqt5hv1UNupbJx3XEbo
            oSU8WxRfIjTAMwOBt9JKqpKV80iMdAoLztFesPn7NfuTCGmkNuMct/A=
            =8xX3
            -----END PGP MESSAGE-----
          fp: 4ec141b4dd5a00e108b36211b0c4aaeff4e05aa6
        - created_at: "2024-11-29T19:58:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA187ia82lSDGARAAv+MSr8fglDJ7DljxGmhOXFajqUSou4A1+kA/owZwQF9T
            PT3iGs3eIF6wXNk/vowmWecWfhUEM8h4gLL4zmzNjvgdxk3lwCBTmctUe897yRLi
            LyK5yITinju5RSrJrS8EaReQxEegPPRUzqPXaaoefEPoCwidi88r1IErRdjFSFJu
            SAYD60gtwdMwcTGHgxVzDkP7GbPuTZelW46oHaZd805iVbektGnlWTjCBHzQM8rB
            13lw1MLuYBJd4oMrIl5mz5g+iVmPcs5U3N0X0Er4vZM+A2Xey6rq3uyPZlJ9GIHF
            vAEo2gNndHn2AzZdbeZWNOCQboSZzawsOHzJfxPfWKDq3b67ewGcRXybYNwcWJri
            AF1kKxOf1qdUrujmNyBJGTD/L4QdnZYdv2CB8+7n8znxo1KWsFj/IGjSp+s8IPsJ
            Mql2JhhQAGrCtCUlnaZqqC4+CTK7YuP7FpouNHh1ykJJFrKGq0AuY5midJZcAOh8
            4OHS/DKm4jneSSQLq/MaXmL2bqeySd33aolkNBahEtRTPFIByA4D07mCJGmKmXLz
            iM5Vx4lI1Csp7S/BGLrkxW5TwiplaDAK9zADpBiClTrvYU50MmFNeUM9iLXSEGQF
            lrxgJOAjPIwOq7uTzeRWyfMaNZJuvvJkUIG1jXYRA3zcweBzrsLT2HZhDzTCNsfS
            WAF2Yu97XwyATMF/HUkzAK7oOc5VD5lcPX4GZU9gdI5ETjQKhLtdj5yd+RHogxVU
            /LyimmbEOh+B1BvoGMIk6mldTRmvon2Mv/Pv0QGGsufAocn776dO2Ws=
            =uIjk
            -----END PGP MESSAGE-----
          fp: a32018133c7afbfd05d5b2795f3b89af369520c6
        - created_at: "2024-11-29T19:58:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4NImSg+4iqHAQ/+JDcsXle7PmmQdrs3mkbERLU9ihHcLtHoCqGRS8JMmqmW
            ud2dHpXln3osN4CnulwzgEx5u8dKEv8tNgU64xhDSLWQLZgqBOuQUb7QAWqpa6e1
            F9y6FBOLmTjjDoBLq+jt8Dcl1yACE17ICM35PfWYnpwhNQAH4Bx9wGSa4rPp7Crx
            M0Hk6EfoVa0Wx7Oxgv8KGJJLUHirGjaBfzU0KndeDLcipl4Eyb8UEDqNH1z4EPMR
            srPhPIbtMtm5Ar9g+VmJ6l2Utg8KTUaJ+r5+u1L0is63MYCfZ3gWrDsxqMIiES/c
            6zm5lSEUI9aMrKUspisghS0eByUHZ5pTFJq9s9jR4WxFGvwryX7DLLwfHlf7YCFV
            bjw13WH/T9AhdzhPyhLxKWEl0qYgwdPwVxCv9y4Jlres532rEz4g3V9mG+WAJYC/
            nXGv0U0/cO5K3YZmJEhSJWi5OpJJOfvI17Tx//SfR0nmRrLKnJQbLEo7qQ9niaEx
            2Tfc2a9M5375Wtm4SG+KCn28Hq23jdEehg80+ZWTjpYhbklHHgroU9nuaPkcXfTa
            ihJuouufBJbenawpzFpyh+SU5aCPzYW7FuDZmEa5QDt9JGsebHpkSlHZkT9I7OWW
            rtElt0Lb7XV6q82At4bwShcuhLZuTkHNMUZfm8jHuD2Fp18n2DLAXgYBiMhcThXS
            WAEvz/+P5ftRimm1eCNnXyuIu1IruEH01kohZGj1UvOpmcBr84I4Tztbsl9FMtys
            2JofmwRDyLjWm4copUkpCTuuIWMq8H5bBC4082EYhLF5LW0tBxfHeZs=
            =9CRK
            -----END PGP MESSAGE-----
          fp: 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
        - created_at: "2024-11-29T19:58:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9T+KNkhS2haAQ//ZGH+tBO/gaBTcxDfEzYJ+xZ+00wxAOAItRDvW1c2wbtJ
            wGnbaaStoyy48K+VwjW/+VhBaJcezccJmUPknFX0eP45dLPKfx+7bkcs9/R6tlJP
            tpBnrDvQZDyTi45GsBBvF529yb22ZAiCUdZ2f6w8QiF97O5njZvXrwQCg874nFHz
            HV5rcm4u5BBmEiMn0bidmhA4Yjb3GAVNaxqF4c3fLG34Bke+QXtu2IulQqAftmHb
            sfHhb0OoO/oD03HAbbKrFQDORwleKNj1D+AUIThdmqmC1moFp2XcqUucmD4H24o1
            uFXjpAzMMp8KmP2UZgIgysVHerz30DA/qnLxmwVHUJjOMcBTiSK8pgVyIEAIXhIj
            cuQlDgZ2Zu1X60g0O77CzmWvFhL9WpoVpLiPfRaGGTmdUj7DzAQEnd52QV2Zh9oj
            M5mTEJvsDyo2faNwhZzKjFrMXUJfJhm/JM8WcOx2Fn37urP1/7Mo51O8U4IhCX5s
            8Ab4cAEe64t21m6MBLoMp3K6ZVd6kMwN3pNu9N91mAn37nSzww0m0YCFIQ0v4JSH
            VhhTfQbUdtSDMVNJNFsaHcHjlt3F3U8gdWUVMRUz5DYk+/bMv8nY3HRXaR79qTYz
            L/ceUEV8CSi4rSm/48hbQm2EPxnPF/k4M2kyN63vo5aGFOpeY6l9CIko9zYLqFHS
            WAF5HO0Ue/Mxu0HrLKCcd3ev4AFztwTqKTKlGnZtuMdOSM+nNdsdsCcRSW4SQ4Th
            jzegpO6f1DWUedypQXdQ6PxYPLUubQwGYwiXpgW20EijToC/Kj9+fW0=
            =Sf0g
            -----END PGP MESSAGE-----
          fp: 05588f4245256f75a8da42e5d4fe28d9214b685a
    unencrypted_suffix: _unencrypted
    version: 3.8.1
