wg-ataraxia: ENC[AES256_GCM,data:DUXlhmTvB5WIJEP7vgr9+YNHlpC0S9Uhcnrp30fvXRehQdGCJvQeOYfHA9ZQ7zl3ZXFHeeM5YbAP0y3eRfvjY27+poW5jzOpj8nv7PB0JKQsF39nYBvWkFg6YpmNYnF6yOWKOK7Ae2cXE4OCWGhGKEtHywv04Mr9b+GgfpFWVxqvanAJ7RFz4nmGf8KK6cKaCyRCeXonEjXh9DfzstIiMYGtBULruw6AZQZP8dRQxoyFQ0/ICIAhiimD5IF/4l8rrdgHYxhn/vZdkhBOfRsH0X19/PiSWdLKAglvCcZK6u0lWEqFMnJFtY77YxXNwEbo5mFN8OVhK0f5T8WGOx5D0dIrkHTaFaOhltMsKwClla5WiYEld5gVuz9TGKoX/W8YANz38fXl2Z2cPShQRN8poHGkTB8iLvVXLx5G3LKMouw01lB+3nrRqZle/THJjFXFhrGla7gGXrKknRq/A/g2CwExiCJIB9num1duTBveQaxSQQ==,iv:h8m/dXC77L6p46rEYIiklZTDUTZgYBg1yiO/klQJGRg=,tag:uEeDkGpaTalFhPT8+R/X7g==,type:str]
wg-dell: ENC[AES256_GCM,data:IUHBtDHFYIhtsO20RGo4Azv2Pc/dbyBvG8F6UJcdtqLRNnl6Q/C/rUZZytsq5tmDeyZ6EJfA8gcEsMcqYdSWhR9lM7cVf/JFGBS4EA82NT+JiV9PzdTahj0eeGEmWsjMsWh74RNkAsOiI3UWIgq3ICuHY4dgWTWmfOz2Fya3uatFwSCgwdCJKJIFIcH/qEdunTL0Rdcj+yykE3OEOGB3ftZFX9cRFhndZhedJKcUdJsBGMauu7w3dFzEbgOd5hUThxaWTWFxStx4DuGNvUtBC1/i/iWM0tpXc0CpnUB6Y0TRW9JKbu0Noo05aQD7neZEK+cJfNLOS7vAu6XRP+hPlqKQQCbvZJRYVhsgVtpNSaIoFtDoL/8kifoyU2JDxWMH1XaqmpWDe3QnpCfh4rAyRRqxP+NdSpBr+Mk5QgTk+zVFhuVFUU38hkbHbIC3uelvYUSNbz7oGOfO1cqBDWlVVJgCg5viiiXodb8NxJVlX/ar32FXq3k52Aajd1NzdFwaWzlUVDEX2OQalf1HpQCdEqRb39NteCtQOii4KCbjod1rT7++H0xProk3L5DyRFeePpjTwbuTqMo0Bg4f5bZ0V484ZoU7Wzho//BrcWw1paKf5rcaVNPZ5grWWCpbrOqc/UVxn0ffi81UpM4c7/rqHj/r60qoWEnvwLWiKFBEd/aJJDZtbp8HH0HS2q7NyXD4X3PHi1CsZoPg3LKbLOxDyUXxihruEhwGe+CYuwFeh2pT7fDhe3AtWw16ThfikjYV/T9PcpHJF4iLupNTKESAbjgges1x2wWVXtqIvPaIe/es9sBEawHKyAJenxoKDu3zLw/efcwQe+PRrzzTlziRjwA8lxl0+Bxf+qx7rrY7eWr4WOjtsbImThJiAagHNRqbtjtCNrm7OsSD4Uob8JlOhpO4F/HSDJDkoncOY/BBVNphOz1xDznJSRLYAavxIcdNnGIBjDIK6pGNFpK1jTqmSVf1W0o2lBnTPrZrbX0nrgAvVJaIdnubrlv/33fAPpvTJF3ymFIVngDBoODXLXcom7OhAEAWAteWQj1V+Xy0xj80QFgWLL6crt2t5qfY6BEbeWvx0mAhFqiwe6sg3CIyQuicdswCRE1Qmq9JPI0MB3Qg92Jbg10rkXx0lXuNptDI9/BrU141NTTuh4FvGF4spqCbpZQd2JAcICauQ2+XBWFwQDdMz57Bqzwc3kPKCCcuf6Yj3ZGt/bcVNV1gsTeyCOzjEVR86a9BL/wOd10niZDh8xfkqEjZ3r8U56+9dlaKrQ3tx2bOX3AAWL0S1D/j9flY5tNX3WaJz/b6aPE3UcK92IcfJzhbYr7pm+NwndSQqdoCcl1QnLPOCcEjnPbkWaw6lORu8LBFnnmGEBPBfikth6uMUW91ZVR8A5qU8xSplUqAVN+cDil5RjyTanrL3tMw+8AHHa/ifYViQJyrxZ7+iEOYrsRf8AFgqVnaDlWfM15knjPYozgjR6C+JqRdDgqHVkZwrrbPSVoCOq2Yf98mR5qVUFwi9BTQOnebPG+H0Yr3jYkdRB7AuN2BKYhvc9NDsznI9rXkQdSTliCmZgPO/TyCGUN8vXvjlXcyh8uIix+vYbhf4yWBIagCf+OvaoOO3NHs0YADNm37dun8x8UHKUcmRXDLvz68oRFNG+SSbPsKZNplCO8Jg2oSwkghrgIfvhfAv8eqNBQ7bGkYqIXVz2PCenVRpXVIYN2TQPt+LjRqaNVfNujeNPDGBBSQ0FM1NmdAHy1dMtuVEZzX2Rmxn5dRO0IK7NwogNIgVC7Jw/mCT+CT9SHhZKpJaHdGOv4O513rFG29Qeyoi6szP5dNNrhOUHGTJZHFLqBtAlTneevR2vnoenVzmr8+xkvJq0wd5UHxoMlNKnF5ex416D2kBpiYBLZP47FUDkfbsYlx+vQbaeiEgT/V4Q4YmZ5h67AoidLISKaFg2dWyeJ2gmmUFON+mPiJmJzoDLCOZimi7GdNk4pjX2qY29pAm7jQdF7j3ZpgyGt/nElRrIEEhek813M2bt25murpEEbgoJf5tR44qgpbdTycdz/G3YLIQ3sgY0RdEm9lkolCO7Pqh4TxSw4WzbSiMUg49cs4z0b62mCBQSr5smTNv0N4+QAsJ8PnCZEgVm0buU12SLtY6Ty7/RWB8Gqb0I5SHUzOvkGEuME4FG9yMiJ7UT+NhdV8Pq4C3TgFeSqDnH0qIkjOgZng4Rl1TEfZvnLq1bjsQIAPl4nfD3RY2+VV,iv:RhPtay1IjAq40plSm5xVzUGbdkCcLwCVsOVysChDGag=,tag:ML99P2YlxsNIdmcxu6hbKw==,type:str]
wg-hypervisor-dns: ENC[AES256_GCM,data:bqiFalZaSx1Xguhufa656uHfyfcCdeXJdtcsWeaGMwBJwO7JXAnFw2eB8y2H4Xr1nrwwravnp3hPmEcLI8eIWUCU+IhNDF0ghkU+YtBcb5HWNRLV9lqqs9dGwEcX9SXQ12lTci0uJxo0nMWcNQWTSALjx7GLHQLmSbmRrGFl5Fxc+NjuAnEH6bQflOVQhjqaUwgYYTOnxdIF6ljDg2+28pfM7RixxKsJc9E7iO9JHYzzwL2Q63w103fIlfroBQ0t6S7gqqB5ahXB/gnr4Cgq4gMFdLdL7LCKPEmpT442wvLt4yjNytdC3P+jxjOK4AHpFHQUps+MH8eapkIrTUhnveITi0dgxOVyAIls+wDYphHEYxXUkkSw+BlCvbygSfHfwj9Lxksn7k1E9D0EN68yNtFpR+72Bfl6H/7BOw==,iv:3GcVUj9EzogzQ78ImEkBfT1Ula28i3dKH2be5Q3ignA=,tag:9+54I6P/JKtmqW5RyOLTLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-21T16:36:51Z"
    mac: ENC[AES256_GCM,data:AmoEIOX4ROFpg60hymSw24oWXs/SodzEvodq7YkUkbeD30woka625KmEwTbpLH6vqaODJU8NS5ioHaFg+ErFY84B+FDz885UYOjeNK0Z/dm4AqjBi3YDxKmfedwpIfzpDO+hDHGOP3/EBALO2Se87Q9hu6NwED+nSRqLqlpPE9w=,iv:tzt2hNr28mSDhTwKBuPVIMhGiD0/KlE/oSx8HICH+Is=,tag:qh29t54uCGxt8flcj43cPw==,type:str]
    pgp:
        - created_at: "2024-01-22T10:23:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwcagTG/Fm6AAQgAi8xG4FM0i4JxqTVLTaZKWzICxfUGdrgVT6lisLiZjSjp
            iR6G1UADtWqJDxUhBN8ZBanvaQfm8goaBaE+iH+2IkYnD/+Exfay1ey1NbInSs2C
            qk8L4WPfRnGCsxjo+tSaciUUcKdH0a+xR0YSgtUctWgsvZ8idQiTV3skdTmDwvR3
            0rlDxtNhjKGuYybvdVhQzM/tTUbzNk1iBwokf8r2aWWi0UmsfAxtH/pHthARyDIl
            7HP98/ek8pZirssb301s94Y3fRRhf0kW04gWNA+/m79OCKxf53vLYkz0HEBRriIC
            +FqHgqn68jFbrbancRI5KpiAfRj1TuAYi7E3ebjkZdJYAfWHLUI8WGekib7v8Fdd
            YljWDrcA9jK6fxEKHky/29qobOVYdqKsTfYDmPwcODvBXUfiS0Ngcg6BDNPLB29h
            JsLYiIb2XeH4bpQiHMmI1+Ms/5e5l9cyeA==
            =TjlY
            -----END PGP MESSAGE-----
          fp: ad382d058c964607b7bbf01b071a8131bf166e80
        - created_at: "2024-01-22T10:23:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzTK+524Lx1AAQ//TqUInIZxoK9rrF1RCF5xCQkL6OKYKuQPNlRxLZ1a8bTG
            W566jpPwRDgmnIx9OpkBzDrVvEfZZN706ACqnjI4dFeVoikPug4TGx3cHxWS61It
            Eh/MfzWUh1+prnIzZEIFK31IHmDXUYNNi0GBai+6cUAEd4guHTeFX4cOMVpuyV26
            fTAdjh0nnMTAKyZbbtDKf2RxhH9/r9jyCia/UJUJD0tukNdxrtiXnENrCL6rBjGk
            WHLhlgscP1qckl1ls8r4J9oCkcrzi29QP3uHvfZLyTyBKXGKcHksHDocbj2TMYnT
            1SXJdr/vwiaxK1B+Eu+t6Q/1FG1983tPWfIkRo4TlzRh8V4NK2fiLTiYV0W6wQks
            cPSnAwAdr2tE6xF7g0Msx1tiyRT+sqf6fmaxZc4FsiFkp9RyufqNsIhW19hg2fsZ
            BdQUEPsp6i3yvMlAnEsSoGpr49fvoEZke0mLU40lbA9bsky9AI0JOitX6Ry4qsuL
            3EwBH7c5KmFERiksfzh14q4SyYZA1HEjvnP1kwEyc5y6/SG92a+fs6H7T1d81uQL
            v8uhKL8V0y0Iip4gSOEIElnQMKnDEGyOo+FN++aOfp91HurqvvYXw9UJ8lh86u0W
            Rmv1jarvJHst0UXnaYBZiSvtmjz1OuBtiFZxbuL1p9LgHrVURHqpNYjZz0Wdd0fS
            WAFKB/ZmHLk+U+D9AzK3E8Sp9tIOSU+/ba2P37T2K0nXV9f97xTHB1+B59mYAmz9
            6XJqhinhwA3+5JXoJ0VT+JcNSReDPNXRDxIWRvQYfQvpk2U2O505vjU=
            =ZcIf
            -----END PGP MESSAGE-----
          fp: 20d2e2b90c6aa179585b6b6b34cafb9db82f1d40
        - created_at: "2024-01-22T10:23:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA187ia82lSDGAQ//TNnXwmVSWHQ+12O/cQt6A+yR49I0ksMn/TgwJS3DhSZ/
            I2X9NGAMQYF04xzwxOIaVDKXntUUDUfCneFWxx5qhSABtJt3+2J46GOt8F8eYzX8
            vMnkBsASHK+EaHfxCmdxYGo2Bba0ALKkU+3vQuSGBO4xZaYWQZys3FMUR+grHdKe
            DM9hfbcgO7pYJ/7wTVxtsI1J68quWE+MnWYjW4PDeTjmXnfePyKLFKFWJ3KRqSRd
            9QzwAKPXW4Jyxt9XQgWMQRAnUBNvaCFnxvmQrdrn8PmYioBZrpYUOId86hp577pX
            11W4sqGl42bW1rPYQD7TPgoL6KHRtGmdz2RvaY28+OKb4W3v3Ul0r+2cr6tkO7Eu
            WoV8pBqNY0KMsb9VjAhrPEllxQ2ZQYx5nURDQmEMMIvomYZVhjxQXCeIQllBUvCk
            DZIzcZ0oWS1kRNcZ0JJQUcC6nZD4lIKZWnq6Yoh+PdpaqFBwUw4+Z2QENN3TuQLY
            H2k0EMgfW0t4NnhtbaAnTQtnhTVX0pun1rZI9id2d+KCwr0XVjhhQCWKrLjXec5s
            i3zxvKuaWvQGtxvr9hFN8QJG+QP7nhaQ75sHZ/5enGWTce1dqWipfBGmI/WpXxcF
            qV22sVCSGAn9SuE0Abe/qXiJaYeRzUfCwoYaDfdlws85qsVfb/qyoRzZI3t7daTS
            WAFW+KMunwYpOdjlqJKMM9ruQY8OBFPYVCvgCxGDxDUSbA7dyZvynBoiFJ/8yBlZ
            jqvYWdF2PFzhCM9/ZNzxIMnEL8m+B9vojJVbJd4M+5yesXHChobN69E=
            =R5Jt
            -----END PGP MESSAGE-----
          fp: a32018133c7afbfd05d5b2795f3b89af369520c6
        - created_at: "2024-01-22T10:23:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4NImSg+4iqHARAA4IYyZNdx5FydXXZL8RPLyiX3ySDgPelLwqRBU7yOsJFH
            JSw4K1p8UNOQCR+ysAu3akzHcNwh+oEOJeJfZDr/UQGomLPq+A7gP36Ai8DsGL13
            KhEqTnRoCvD2OXSGMx0jjy++ZpniCGmQYDcY1uzOqTq4Q0P4k4bA3qzZz3H2dTUV
            cl7IiHNtZX/ogJe9DCdSIFjUds1LGii/oeAaf4jLzaO3V9jhh8p7aJVyhVV7CJrf
            x/0vx7cWp2kjRRqs0IXaWJ0A35bG1SN5xSU8ohAcagIA8t3WVq0E0iaj7unXMySe
            2b9RGd+sqS9PlRb43x+xRlkII6oIQhBZCpIHFWWZFNwegp4UtJt1GXJl9hsVrqL/
            fO7l9HWXZTGCYSVZJ/lsC8b4cSobIxGd/tAwVzx9xc/EAmY/2WABiC7uZjk0gqPx
            iAT/Qzbl0M/u7ZopU+I0DGv1dwClEIvJPd8Tz8AiF5idWzONUyGydu5itQCXAnpD
            zSNoB+NDINnVdRTCE7kxp07euNkrScjC4x4ruOLzIMLWleDPiqxQJ7NLNG2/N5PG
            GOlxp3uTmBOkCaPE3KBIlLBus0XGT2oq0mX+DIP8Wk2oJtOvVrYiMYUV7CVppi9h
            xZ+4VejHXbRpJOSKuZf4lji5b2DspSee6scgjoUkLDt0Zp0bqIKJ5TbxFAdNA+zS
            WAFv2BsueDg3gm8HYmSZP855Osg3+StrX67sjGst/dwUrSczQyKt4g9JJ2LOVU+j
            YTDJvhNcBG3GHWnVZl1yE97i46KMDL4uIz/P5TgCIuvvhmGVtabIYx0=
            =MHAW
            -----END PGP MESSAGE-----
          fp: 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
    unencrypted_suffix: _unencrypted
    version: 3.8.1
