wg-ataraxia: ENC[AES256_GCM,data:DUXlhmTvB5WIJEP7vgr9+YNHlpC0S9Uhcnrp30fvXRehQdGCJvQeOYfHA9ZQ7zl3ZXFHeeM5YbAP0y3eRfvjY27+poW5jzOpj8nv7PB0JKQsF39nYBvWkFg6YpmNYnF6yOWKOK7Ae2cXE4OCWGhGKEtHywv04Mr9b+GgfpFWVxqvanAJ7RFz4nmGf8KK6cKaCyRCeXonEjXh9DfzstIiMYGtBULruw6AZQZP8dRQxoyFQ0/ICIAhiimD5IF/4l8rrdgHYxhn/vZdkhBOfRsH0X19/PiSWdLKAglvCcZK6u0lWEqFMnJFtY77YxXNwEbo5mFN8OVhK0f5T8WGOx5D0dIrkHTaFaOhltMsKwClla5WiYEld5gVuz9TGKoX/W8YANz38fXl2Z2cPShQRN8poHGkTB8iLvVXLx5G3LKMouw01lB+3nrRqZle/THJjFXFhrGla7gGXrKknRq/A/g2CwExiCJIB9num1duTBveQaxSQQ==,iv:h8m/dXC77L6p46rEYIiklZTDUTZgYBg1yiO/klQJGRg=,tag:uEeDkGpaTalFhPT8+R/X7g==,type:str]
wg-dell: ENC[AES256_GCM,data:IUHBtDHFYIhtsO20RGo4Azv2Pc/dbyBvG8F6UJcdtqLRNnl6Q/C/rUZZytsq5tmDeyZ6EJfA8gcEsMcqYdSWhR9lM7cVf/JFGBS4EA82NT+JiV9PzdTahj0eeGEmWsjMsWh74RNkAsOiI3UWIgq3ICuHY4dgWTWmfOz2Fya3uatFwSCgwdCJKJIFIcH/qEdunTL0Rdcj+yykE3OEOGB3ftZFX9cRFhndZhedJKcUdJsBGMauu7w3dFzEbgOd5hUThxaWTWFxStx4DuGNvUtBC1/i/iWM0tpXc0CpnUB6Y0TRW9JKbu0Noo05aQD7neZEK+cJfNLOS7vAu6XRP+hPlqKQQCbvZJRYVhsgVtpNSaIoFtDoL/8kifoyU2JDxWMH1XaqmpWDe3QnpCfh4rAyRRqxP+NdSpBr+Mk5QgTk+zVFhuVFUU38hkbHbIC3uelvYUSNbz7oGOfO1cqBDWlVVJgCg5viiiXodb8NxJVlX/ar32FXq3k52Aajd1NzdFwaWzlUVDEX2OQalf1HpQCdEqRb39NteCtQOii4KCbjod1rT7++H0xProk3L5DyRFeePpjTwbuTqMo0Bg4f5bZ0V484ZoU7Wzho//BrcWw1paKf5rcaVNPZ5grWWCpbrOqc/UVxn0ffi81UpM4c7/rqHj/r60qoWEnvwLWiKFBEd/aJJDZtbp8HH0HS2q7NyXD4X3PHi1CsZoPg3LKbLOxDyUXxihruEhwGe+CYuwFeh2pT7fDhe3AtWw16ThfikjYV/T9PcpHJF4iLupNTKESAbjgges1x2wWVXtqIvPaIe/es9sBEawHKyAJenxoKDu3zLw/efcwQe+PRrzzTlziRjwA8lxl0+Bxf+qx7rrY7eWr4WOjtsbImThJiAagHNRqbtjtCNrm7OsSD4Uob8JlOhpO4F/HSDJDkoncOY/BBVNphOz1xDznJSRLYAavxIcdNnGIBjDIK6pGNFpK1jTqmSVf1W0o2lBnTPrZrbX0nrgAvVJaIdnubrlv/33fAPpvTJF3ymFIVngDBoODXLXcom7OhAEAWAteWQj1V+Xy0xj80QFgWLL6crt2t5qfY6BEbeWvx0mAhFqiwe6sg3CIyQuicdswCRE1Qmq9JPI0MB3Qg92Jbg10rkXx0lXuNptDI9/BrU141NTTuh4FvGF4spqCbpZQd2JAcICauQ2+XBWFwQDdMz57Bqzwc3kPKCCcuf6Yj3ZGt/bcVNV1gsTeyCOzjEVR86a9BL/wOd10niZDh8xfkqEjZ3r8U56+9dlaKrQ3tx2bOX3AAWL0S1D/j9flY5tNX3WaJz/b6aPE3UcK92IcfJzhbYr7pm+NwndSQqdoCcl1QnLPOCcEjnPbkWaw6lORu8LBFnnmGEBPBfikth6uMUW91ZVR8A5qU8xSplUqAVN+cDil5RjyTanrL3tMw+8AHHa/ifYViQJyrxZ7+iEOYrsRf8AFgqVnaDlWfM15knjPYozgjR6C+JqRdDgqHVkZwrrbPSVoCOq2Yf98mR5qVUFwi9BTQOnebPG+H0Yr3jYkdRB7AuN2BKYhvc9NDsznI9rXkQdSTliCmZgPO/TyCGUN8vXvjlXcyh8uIix+vYbhf4yWBIagCf+OvaoOO3NHs0YADNm37dun8x8UHKUcmRXDLvz68oRFNG+SSbPsKZNplCO8Jg2oSwkghrgIfvhfAv8eqNBQ7bGkYqIXVz2PCenVRpXVIYN2TQPt+LjRqaNVfNujeNPDGBBSQ0FM1NmdAHy1dMtuVEZzX2Rmxn5dRO0IK7NwogNIgVC7Jw/mCT+CT9SHhZKpJaHdGOv4O513rFG29Qeyoi6szP5dNNrhOUHGTJZHFLqBtAlTneevR2vnoenVzmr8+xkvJq0wd5UHxoMlNKnF5ex416D2kBpiYBLZP47FUDkfbsYlx+vQbaeiEgT/V4Q4YmZ5h67AoidLISKaFg2dWyeJ2gmmUFON+mPiJmJzoDLCOZimi7GdNk4pjX2qY29pAm7jQdF7j3ZpgyGt/nElRrIEEhek813M2bt25murpEEbgoJf5tR44qgpbdTycdz/G3YLIQ3sgY0RdEm9lkolCO7Pqh4TxSw4WzbSiMUg49cs4z0b62mCBQSr5smTNv0N4+QAsJ8PnCZEgVm0buU12SLtY6Ty7/RWB8Gqb0I5SHUzOvkGEuME4FG9yMiJ7UT+NhdV8Pq4C3TgFeSqDnH0qIkjOgZng4Rl1TEfZvnLq1bjsQIAPl4nfD3RY2+VV,iv:RhPtay1IjAq40plSm5xVzUGbdkCcLwCVsOVysChDGag=,tag:ML99P2YlxsNIdmcxu6hbKw==,type:str]
wg-hypervisor-dns: ENC[AES256_GCM,data:bqiFalZaSx1Xguhufa656uHfyfcCdeXJdtcsWeaGMwBJwO7JXAnFw2eB8y2H4Xr1nrwwravnp3hPmEcLI8eIWUCU+IhNDF0ghkU+YtBcb5HWNRLV9lqqs9dGwEcX9SXQ12lTci0uJxo0nMWcNQWTSALjx7GLHQLmSbmRrGFl5Fxc+NjuAnEH6bQflOVQhjqaUwgYYTOnxdIF6ljDg2+28pfM7RixxKsJc9E7iO9JHYzzwL2Q63w103fIlfroBQ0t6S7gqqB5ahXB/gnr4Cgq4gMFdLdL7LCKPEmpT442wvLt4yjNytdC3P+jxjOK4AHpFHQUps+MH8eapkIrTUhnveITi0dgxOVyAIls+wDYphHEYxXUkkSw+BlCvbygSfHfwj9Lxksn7k1E9D0EN68yNtFpR+72Bfl6H/7BOw==,iv:3GcVUj9EzogzQ78ImEkBfT1Ula28i3dKH2be5Q3ignA=,tag:9+54I6P/JKtmqW5RyOLTLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-21T16:36:51Z"
    mac: ENC[AES256_GCM,data:AmoEIOX4ROFpg60hymSw24oWXs/SodzEvodq7YkUkbeD30woka625KmEwTbpLH6vqaODJU8NS5ioHaFg+ErFY84B+FDz885UYOjeNK0Z/dm4AqjBi3YDxKmfedwpIfzpDO+hDHGOP3/EBALO2Se87Q9hu6NwED+nSRqLqlpPE9w=,iv:tzt2hNr28mSDhTwKBuPVIMhGiD0/KlE/oSx8HICH+Is=,tag:qh29t54uCGxt8flcj43cPw==,type:str]
    pgp:
        - created_at: "2024-02-06T20:12:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwcagTG/Fm6AAQf8CdTzbc5BPBdvB0NhTjXOg0olukifCDNaQDFmiOGQvocq
            BA4dDlfpXpNNmY+HU5ainMjxUbT7hkFEHTnII3KBJ7KgWa2JBEfaMonLfZDNnBU5
            gre3bslABdObU0gmt1SuBNaKbKalfZ9uifbia/35/ZJYt/LSL3H+a964kuAP58eF
            Pn8V9gjjcsNGGmsHbwLShwbH9l47J7DAsKVCpXED8VHzxRHUbIkhMszNmcuwpV0c
            3EpdrJeL/oqCL9qaJeXBOccvx4EE9k7TzHoZhvb7uO/53e3BzQVTnjmRkkvUxyNA
            8rdUD7tP0gbsXk7arkScL3IpvjGSh1qZPyLX5RoZ89JYAXM7fZRubTo2aJsd7UAN
            YOqM1BVYJNfWC8wEQwK+/Pk2e3kFBD7+CKG41DhGls5wltCgf0+WKEfXaWFRLENq
            w2imyoPGod0ndAsKuelrOYC8wppX4C5txg==
            =+bnw
            -----END PGP MESSAGE-----
          fp: ad382d058c964607b7bbf01b071a8131bf166e80
        - created_at: "2024-02-06T20:12:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzTK+524Lx1AARAAll9gaPNg+LG/SC+IKmIuxO2cpl3TUpBNbAy0Wfq0n0ck
            Vs6x5P1a88vIzQqBqr8b0tMZXJcLMOsTQwU64uHPgW+9zezcOpuPDv/uJHh3ySWw
            r0+lvfve5acHky3NZBEvesSWKz0MTha5qvQsvVdFWXC4TZcX9YE50O6o/mMjM0ZN
            BgVMj8hHn2tyQ2jsRFJn/6NAEfYIn2sM/qz9Dp0p3IqM/KHzv1zShPxFRx31Ipk6
            fn+bKmhV3XqNeahE183a6N4/JMZr2EWVJqIbMkSy9h11C2w+d1U2bcQUMUNV+JOn
            Kxgw4tWrMOwrse02VT00yKFEVUi0vHxtTOn5Z4IQKiGXXBCR7CEr/WZ3xLSYn+lN
            QtFY1ZETCIIvCjbC4m3IyqDDuCQNcmRbCqlUHQWH4e4aIaWpMdZFNQQB/SbvnUTK
            GmS0hg0aB0n/Pz6mytaAWdN4yb6vUPhGWcHRkU5veYJ3bnKISKchUmyiLa15oLIN
            Aup+vN6mA/z9807g5lVCanfxrI6mb29lm9EUQBG6DoG6jzzRhjbf0/a0/WgZ80B1
            YDxIYjNxd0w1WDK0YfPAclh+MXj0DeaqN3c9SlBUd27cRe2+pWZzpll2GLyRPUA5
            cB0qqmwztmWQ93cvQnV9WHFkq9gq+Fu/evdCyClS1rnZOoM7130c2ieTD/AuZkrS
            WAGPCeD6Rpb+/uj0GfU/AnkciWeiSzNXX7cNeyBVfiRHAX3Fq9Pjmepb5NyOr+eH
            BmxX9sumGVng3VZbFJL91v+Prcf2Y2kMKxd16FDgHgZ69xuIbwj26Gs=
            =6AX2
            -----END PGP MESSAGE-----
          fp: 20d2e2b90c6aa179585b6b6b34cafb9db82f1d40
        - created_at: "2024-02-06T20:12:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA187ia82lSDGARAAgCBjWbJ5KlQwwK3/HHvd4t2pa9X4zm4MJ7TgWVr/Drc2
            shesUZV4BhZdTCVZXFSQSzBmCn3UmrIKvtXRrwAvONWpkPILPl8M9eERiXN2isEv
            w0ws2ZhDRYiyXt1JvGNbCpsQByn2B0iHDSgWfazrapEuVzIIifGLorkL8d7SDh5N
            QuBihmMGgLcLrw2DyOCPnlIxNkqtjPbCFXfVxiWqQZqipFAozcOjsWMYf0LtFyER
            a0J7e6jRtz/yxlgHiOdfBSwlmL6lcQ4vxzJc/m1aUO0ZyAvCMtTm9RntDISobtEc
            Fj0IPA0RLFNNgedpCsH0OoW3PJBjToJprgdji13gywfBqczCVG4L68WhT4w2FPBi
            anEvRZTnX+hdNQbU1cdmq+DavN14Kc1l23S1//APjf9mDafvqKxSoF3/ZExm1Ops
            uVJ+e5ofWjpoBWLSFDLT2K5YvBVqCAE6g29tAswvSlRnFOSs7vVM7aknKdFYnh4q
            FN/3AKp86NKuEwaQvjCz7Rwp+dnGCgAQaYapSm8lYzcm2MeVosYXK4ysQmxMI8U1
            Z6w3SmJfPzwL7YLuPzf+n3/fFeOhFITN3m2RrZhnn1hfJsakZS1AfpBm9RNShdsc
            El+tCjdMKGlXNADK8WcSt2bP5wRa0VvYoUS2D0NHg2INqP51SdTzw6I0IGe2bOnS
            WAEetWxRuGJ6P5cyq9qAIGp5yc3+YwHKJmGt601DtAnGdp9d3faZeWLIWd2mDG2c
            hX70jMySCXklSd/V2gxEZakHTTcVyjc5D+rJDmiL/5gYk24IOJnkTP8=
            =5Egj
            -----END PGP MESSAGE-----
          fp: a32018133c7afbfd05d5b2795f3b89af369520c6
        - created_at: "2024-02-06T20:12:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4NImSg+4iqHAQ/+NwqmLTrE03DzG4q7jgc8r9QoKo6fAAevEGuTQjl2ox54
            NLJH997poRH2hyjvtpWp0GtPXcOhCWXWdNGd5/mm78+r3FknriXC9XcP1+nQypen
            WcnMHxsSljZikza2eG78DCz7CvRProl/Ug/YCu1va+jmoXJ53cgw1WeC7OI9178X
            fSbmKeocEL68u0dnJRYZHNgzYz83tiLBQv0HCXr9nPNIEqjRemi3NnIAIETWq+rY
            aDE4kdKlBDPW03Ra1HrmYXkGgQ2N9mWGhvOBt9R9kNyDdo1vGY/FU78NnwQzphWU
            QZzUI4Ldyfx4xs1wQRs5+pWiVClw5UjmR/lTRDmaKWyIhJYIDlDxF1+IK2YWfAdn
            9PdSWrjJzSJcYAwtx+rdQ8EM1MhuA0RF1dQbjVZTLLuPJODqX4oV2s1qY406XpCT
            nnlxwvyroFg3C3cg0wW3rSltoVXiuMknpNviMfXJWMjM2Bl0Akz10StEvwQrwmEy
            ZJ9AHSCopFMMPyOuQT23wUSk0NeAhNC7PSjriS/pMnaOXcyp4mkBOw/aLmQLqxpf
            JQnzfJc9TaXxlPr9HuFtan1IDwJOcVwpZD/n5AAmXQyf94aN26O7qgFPFXi6WpX6
            pea/QaZDH4t+pv01jIQl3u1NY2rsyHq9kDJux0SPEf6LfMVQ683oi0N1fJfBolbS
            WAHTmUC1s6JVTBjVqlDNAbQ155G0Zl0/B1GnI+q90uEfW4NlybJlgR2HmOtH7Kad
            dXsz2SEuCIGguMTjlm09jFd5use1R8UoYKRl24QFQjNAOfEp0N2NVOQ=
            =ZA8m
            -----END PGP MESSAGE-----
          fp: 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
        - created_at: "2024-02-06T20:12:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9T+KNkhS2haARAAgUlmj09aCdfVy9wQWRNNf3ALZlpDUfkTK6ZNVj2sGzTS
            vLs6kfXyFo2aEUYmD5dKSaQf+Yc4GnoVed5iJkGoTxHe6UXDjO4/TJn+AIdgp0uZ
            t07KMO9+cUC5q8lXXz9ybX9uosSCAKwnsDylU9YmEGmDSAZNtmtOnWm3RhBd4DyG
            SylEcSORfCUFUFATPHU3FqZtLVCx/50DmoNR5V4qVzKLVnSI//TQtm440iFBGJV+
            2KzLYd04H7npoCAVkoxWAp00+4pqcq5+cHASOANzG60bsGCUbXePr8zgvNDTJzCa
            CgfC1qOGWgyu9fxy12O3b1qf9rkAEva2Amw/sJS8RddBIFClEQ80TCqwOk3VvUJ1
            Ywnhw8F5zpNBKFE0HIQsGpexcVjJFHLCklo7PXx5W1dJepkUl38h3DwiAhyTiNp0
            XNtU4P4TEOLjKdhuG5CDOcpMJ98Z8jIDiNTqP8pPj6Zk3oUZEVWQV1GthM3vdXES
            xRTlTJqv6UqEhnRcS8tpqpZVDiR4LYS4w0NcnabPKyvVnn3RoTb08O7RACdIfCGZ
            4olWIC0zxNwMUfzCB153ZAfXBJqBNKbZddjvhqfAHnp3wukSSv72rVTYuC52HS8Y
            4Y78+53oKILHZVVpsZvGwiywJFtUXVFH7Vh//NJUE0zRFtVsCFH1M4SczGRylQ/S
            WAFxDCu7bnSSjZKjF8iOY52WNynOv+dpryh5AAMv8HRq8r76gGhKUyJuMpveFdIF
            Cog59tGcH73LBfwHlwlMyVgSjsiAtYGVe3xVqjNjv1GquzCKW9wq2UI=
            =nakl
            -----END PGP MESSAGE-----
          fp: 05588f4245256f75a8da42e5d4fe28d9214b685a
    unencrypted_suffix: _unencrypted
    version: 3.8.1
