wg-ataraxia: ENC[AES256_GCM,data:DUXlhmTvB5WIJEP7vgr9+YNHlpC0S9Uhcnrp30fvXRehQdGCJvQeOYfHA9ZQ7zl3ZXFHeeM5YbAP0y3eRfvjY27+poW5jzOpj8nv7PB0JKQsF39nYBvWkFg6YpmNYnF6yOWKOK7Ae2cXE4OCWGhGKEtHywv04Mr9b+GgfpFWVxqvanAJ7RFz4nmGf8KK6cKaCyRCeXonEjXh9DfzstIiMYGtBULruw6AZQZP8dRQxoyFQ0/ICIAhiimD5IF/4l8rrdgHYxhn/vZdkhBOfRsH0X19/PiSWdLKAglvCcZK6u0lWEqFMnJFtY77YxXNwEbo5mFN8OVhK0f5T8WGOx5D0dIrkHTaFaOhltMsKwClla5WiYEld5gVuz9TGKoX/W8YANz38fXl2Z2cPShQRN8poHGkTB8iLvVXLx5G3LKMouw01lB+3nrRqZle/THJjFXFhrGla7gGXrKknRq/A/g2CwExiCJIB9num1duTBveQaxSQQ==,iv:h8m/dXC77L6p46rEYIiklZTDUTZgYBg1yiO/klQJGRg=,tag:uEeDkGpaTalFhPT8+R/X7g==,type:str]
wg-dell: ENC[AES256_GCM,data:IUHBtDHFYIhtsO20RGo4Azv2Pc/dbyBvG8F6UJcdtqLRNnl6Q/C/rUZZytsq5tmDeyZ6EJfA8gcEsMcqYdSWhR9lM7cVf/JFGBS4EA82NT+JiV9PzdTahj0eeGEmWsjMsWh74RNkAsOiI3UWIgq3ICuHY4dgWTWmfOz2Fya3uatFwSCgwdCJKJIFIcH/qEdunTL0Rdcj+yykE3OEOGB3ftZFX9cRFhndZhedJKcUdJsBGMauu7w3dFzEbgOd5hUThxaWTWFxStx4DuGNvUtBC1/i/iWM0tpXc0CpnUB6Y0TRW9JKbu0Noo05aQD7neZEK+cJfNLOS7vAu6XRP+hPlqKQQCbvZJRYVhsgVtpNSaIoFtDoL/8kifoyU2JDxWMH1XaqmpWDe3QnpCfh4rAyRRqxP+NdSpBr+Mk5QgTk+zVFhuVFUU38hkbHbIC3uelvYUSNbz7oGOfO1cqBDWlVVJgCg5viiiXodb8NxJVlX/ar32FXq3k52Aajd1NzdFwaWzlUVDEX2OQalf1HpQCdEqRb39NteCtQOii4KCbjod1rT7++H0xProk3L5DyRFeePpjTwbuTqMo0Bg4f5bZ0V484ZoU7Wzho//BrcWw1paKf5rcaVNPZ5grWWCpbrOqc/UVxn0ffi81UpM4c7/rqHj/r60qoWEnvwLWiKFBEd/aJJDZtbp8HH0HS2q7NyXD4X3PHi1CsZoPg3LKbLOxDyUXxihruEhwGe+CYuwFeh2pT7fDhe3AtWw16ThfikjYV/T9PcpHJF4iLupNTKESAbjgges1x2wWVXtqIvPaIe/es9sBEawHKyAJenxoKDu3zLw/efcwQe+PRrzzTlziRjwA8lxl0+Bxf+qx7rrY7eWr4WOjtsbImThJiAagHNRqbtjtCNrm7OsSD4Uob8JlOhpO4F/HSDJDkoncOY/BBVNphOz1xDznJSRLYAavxIcdNnGIBjDIK6pGNFpK1jTqmSVf1W0o2lBnTPrZrbX0nrgAvVJaIdnubrlv/33fAPpvTJF3ymFIVngDBoODXLXcom7OhAEAWAteWQj1V+Xy0xj80QFgWLL6crt2t5qfY6BEbeWvx0mAhFqiwe6sg3CIyQuicdswCRE1Qmq9JPI0MB3Qg92Jbg10rkXx0lXuNptDI9/BrU141NTTuh4FvGF4spqCbpZQd2JAcICauQ2+XBWFwQDdMz57Bqzwc3kPKCCcuf6Yj3ZGt/bcVNV1gsTeyCOzjEVR86a9BL/wOd10niZDh8xfkqEjZ3r8U56+9dlaKrQ3tx2bOX3AAWL0S1D/j9flY5tNX3WaJz/b6aPE3UcK92IcfJzhbYr7pm+NwndSQqdoCcl1QnLPOCcEjnPbkWaw6lORu8LBFnnmGEBPBfikth6uMUW91ZVR8A5qU8xSplUqAVN+cDil5RjyTanrL3tMw+8AHHa/ifYViQJyrxZ7+iEOYrsRf8AFgqVnaDlWfM15knjPYozgjR6C+JqRdDgqHVkZwrrbPSVoCOq2Yf98mR5qVUFwi9BTQOnebPG+H0Yr3jYkdRB7AuN2BKYhvc9NDsznI9rXkQdSTliCmZgPO/TyCGUN8vXvjlXcyh8uIix+vYbhf4yWBIagCf+OvaoOO3NHs0YADNm37dun8x8UHKUcmRXDLvz68oRFNG+SSbPsKZNplCO8Jg2oSwkghrgIfvhfAv8eqNBQ7bGkYqIXVz2PCenVRpXVIYN2TQPt+LjRqaNVfNujeNPDGBBSQ0FM1NmdAHy1dMtuVEZzX2Rmxn5dRO0IK7NwogNIgVC7Jw/mCT+CT9SHhZKpJaHdGOv4O513rFG29Qeyoi6szP5dNNrhOUHGTJZHFLqBtAlTneevR2vnoenVzmr8+xkvJq0wd5UHxoMlNKnF5ex416D2kBpiYBLZP47FUDkfbsYlx+vQbaeiEgT/V4Q4YmZ5h67AoidLISKaFg2dWyeJ2gmmUFON+mPiJmJzoDLCOZimi7GdNk4pjX2qY29pAm7jQdF7j3ZpgyGt/nElRrIEEhek813M2bt25murpEEbgoJf5tR44qgpbdTycdz/G3YLIQ3sgY0RdEm9lkolCO7Pqh4TxSw4WzbSiMUg49cs4z0b62mCBQSr5smTNv0N4+QAsJ8PnCZEgVm0buU12SLtY6Ty7/RWB8Gqb0I5SHUzOvkGEuME4FG9yMiJ7UT+NhdV8Pq4C3TgFeSqDnH0qIkjOgZng4Rl1TEfZvnLq1bjsQIAPl4nfD3RY2+VV,iv:RhPtay1IjAq40plSm5xVzUGbdkCcLwCVsOVysChDGag=,tag:ML99P2YlxsNIdmcxu6hbKw==,type:str]
wg-hypervisor-dns: ENC[AES256_GCM,data:bqiFalZaSx1Xguhufa656uHfyfcCdeXJdtcsWeaGMwBJwO7JXAnFw2eB8y2H4Xr1nrwwravnp3hPmEcLI8eIWUCU+IhNDF0ghkU+YtBcb5HWNRLV9lqqs9dGwEcX9SXQ12lTci0uJxo0nMWcNQWTSALjx7GLHQLmSbmRrGFl5Fxc+NjuAnEH6bQflOVQhjqaUwgYYTOnxdIF6ljDg2+28pfM7RixxKsJc9E7iO9JHYzzwL2Q63w103fIlfroBQ0t6S7gqqB5ahXB/gnr4Cgq4gMFdLdL7LCKPEmpT442wvLt4yjNytdC3P+jxjOK4AHpFHQUps+MH8eapkIrTUhnveITi0dgxOVyAIls+wDYphHEYxXUkkSw+BlCvbygSfHfwj9Lxksn7k1E9D0EN68yNtFpR+72Bfl6H/7BOw==,iv:3GcVUj9EzogzQ78ImEkBfT1Ula28i3dKH2be5Q3ignA=,tag:9+54I6P/JKtmqW5RyOLTLw==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n0prg9vynuwc56gn0xfe5qde8wqcd4uzg5ghhhetu2024ckvjyvqxf49el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTWtVKzlTdVRqMFdNSkdo
            cXZKSkUyT2ZmSDdjNlo1NWpqaVdFWkRHZjBZCmErOVgxQlExODQ3MVF4aUFPZzNh
            L0UzMGVrZjMvQ2FsbE9CbERqOG1YbzgKLS0tIEhuUWFnaWh0TURNaW9SMzl0allk
            QkRwWHF3ZkN2Nk45SndmM2d4NmdrSVEKoBbfU/xjR8rAG7+mMqlDmJcoxw9lpZjN
            gSgqlVKo0a56uo4Sn//bJobV2xqFzHMnVJba0cgAG4GhhGn1TR9yCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ztrteyc2hae7c0tlrjx9pcjjtyeqazsq7ztf7dcmxlyxg5x2mcwq75p65f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWFEyWGFabUxTM0gvTGdD
            dS9lNldCQlgyUHhESXNtZHBkRmNPWEl1aFJVCjVVSXpxQjZQTzdQN1l6eFZKZnYr
            OUFqMFpZa2JMY3FZcWRvVGsxa3dnNzAKLS0tIHhOdGxyc3RLeHF4R3VDYlVxbG5D
            T3dIWENKblB5dU1hZUpZeUp1a2VPZmsKYaJOSxFUZ/AtmsJF+5EDeroSBLHIwDP0
            aht3h4oqJhfbjDfjMKc0oqSebyFyZ3ibIP7hJ3nia8ejKBOKc+KaUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m5msm7rgqye2q9zesgedg0emga4ntehlr629786lrxs3rhk0squq0ly9je
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYS9JV3cwU3VZOEJFRG9N
            TENubUsyRTZvWll6dGJPZ0dwbTA2Z285QjB3CjZDRGJndlY3VUdPQ2lJenJIQzhv
            K0syS1pabWpCZUkxSllhd2tIVU5EUDgKLS0tICsvUkZjOFdLSFc1TFAwTTU1cXQz
            L25nclJmbFg0OHh3VC94ZDJvQllWb1kK83k9R2klidEKDCLV7msD7pCkkT1B3907
            uzgzN2GRd2VU7D6loeDtOSA1wpXoi8/u2nEgh3Rz1M759681DjTWhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xxakyntj60nds474xyhpqtl2cvyktefrqcd79x5ava6amewzugmq60rcdh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSFJHYkFEenhDT1p3MjBz
            K2tXSldBbWVGR21tTElMRWhSZ2R3elRsVXhjCjNXb1VnMEZKaUR5Nmh1aXhxL1Mw
            UlB2OUNuaCtyOHRCUFBqK2RXa1FFcWcKLS0tIGg3MTFvTXRhd0p2NFB0ZEhGZEFn
            R25PZkd2TnRVK2YzcWpEdXZFZnlRamMKQ3RHdNbxVRTF5A9bJ27MesW278VFrWcU
            cpeIIiGBxNzxcnAhXccpxf48CqFj2owIOB8xmnX0dIiO+nU/m4yj5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d4mqql020mpne9r3vtt4l9ywfzfq7zpa3mad33syxln2kldkjsxqgju90f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeG9ON2lXRW1LbVk5UUIr
            RTEzMFFsTUU3dmY5L1JDTS9zQlM3MnErdnhVClFXTGc1dUtYVHIxaGF0ZjQ3elV6
            cVhwRm51eC9JM3lKbW1OSTZwY3BRVjAKLS0tIFhwNndnaUY4VGRRUzdOa1U3K1JM
            UEZqRWJNZjd4RFptTk9OWEErbHBvbWMK90yq99mEYF+BgBQa2mnUXOVUgM0eRYwV
            zsBOJiWb/RRDCA29ySBZN/g+oHo+dFwMHPurfgfOrk2KywoHSL8KtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T16:36:51Z"
    mac: ENC[AES256_GCM,data:AmoEIOX4ROFpg60hymSw24oWXs/SodzEvodq7YkUkbeD30woka625KmEwTbpLH6vqaODJU8NS5ioHaFg+ErFY84B+FDz885UYOjeNK0Z/dm4AqjBi3YDxKmfedwpIfzpDO+hDHGOP3/EBALO2Se87Q9hu6NwED+nSRqLqlpPE9w=,iv:tzt2hNr28mSDhTwKBuPVIMhGiD0/KlE/oSx8HICH+Is=,tag:qh29t54uCGxt8flcj43cPw==,type:str]
    pgp:
        - created_at: "2025-02-23T11:33:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwcagTG/Fm6AAQgAkNLLePnS/Uu7SmBc56B9UMgvz4PiANxFz5r9jRbVvOup
            AdNmwGORQ4oH39TdygTjMUD2tVuX1rPqPXXMdpVR7U5HbJcOqCtrDZ+y2yG/krvV
            VeYtGI7tNvQvr2jOywPtyHOGzAD+3iy7URsnM0O1f/ivfry7TTgg0K5XNx6Dr9Lr
            jS0c9cL1byY+Xjkac3qNbLnky/oA+x2a0VrgM2+fkxk5g6IQn+0b03ac079rsPJh
            xxDTx0YWuAsMNUtp3Od67Pg23IGScGYYu/pOOG5bQrYCwmu0nZqzKQD7U1umIzNe
            T01HhonqXyzAld7oHylNmZLXxnkQZnKofOrUXk1XudJYATUpJyvMsxoV5d62Y7yw
            8XN4w46wTUxHjfsizZfCmCsxjlUIudzR4NEybqPOESmrVaBoPORwTD13b3USGSCj
            fOEUnYjRL27ta6tUkq7xFBgARfP4KtisJg==
            =1whR
            -----END PGP MESSAGE-----
          fp: ad382d058c964607b7bbf01b071a8131bf166e80
        - created_at: "2025-02-23T11:33:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7DEqu/04FqmAQ/8D9a7sxtGdQr0HNk2XKog2H4+XZ3tepIg36SM6lxFde7H
            hjj/BSMFnh3INtHMZtaPka6z9HlRk5g08ieBc/HFuIbn0TV3WiQZfFKwngNAfftN
            ZfgyNSKo06TU3lnJIYqKVSk/fev1he9Tki9aED4OB1FkEwS8gNfgdIsdYg8fqEKu
            YXzgPbJGEUJrmjpS9gDY0xMxXj0r6XaIjvUiO9L/1IvKs3yPXZs1FvCkRkD41UFE
            sZwWhfrOQDXjena5YSBM3QG/AdoHoA1y9W/urKaLquCR547RMBuFhq4uRGxWQE54
            sZ5P/czE4S/3AfBx775R96ssZvVmUU+0s+RU6p2hlU5ohi3A6atAwYy6nWdNsqPA
            we2gxp0KlgRDhdtIn/41WVcmfcIAaBfgk1uHQWfP2rFQs7XbhKU2WbIb8IlHZWAt
            AA8UB2buCWoWnFhpJoAAhOFfl3o16FfnZXs/6WUxCC9g4zTvD4+wima/DFE+WQpN
            out77ty2PDZ90hlUUenI2VucQRD1a6z82tqEnWM/N9CrzPnbK+N2pHsoiOhAMiSU
            bSJSc0Kl74T8RVdHdVl/+25JJtb4C6b/8uY7stov+Xj9XUMesd1cta4kEvGAJpix
            JKk16C/goR2lLe/K7tYfiWlAEvJrqRlw8p2xsps33a1fekoNRVcNIGo6dUWKOKLS
            WAG8CFfZkGhAao4RF3zZk5J2YwMlYQ7nQK2ATOQCQ2tYZmLUbB3oHO5jQOHgnQmr
            o4oXrwy/0ecFVqpLpOeTjL732SzNxdOlpZxoBrc8iCWVeD3KIGz2rW0=
            =1Pyp
            -----END PGP MESSAGE-----
          fp: 4ec141b4dd5a00e108b36211b0c4aaeff4e05aa6
        - created_at: "2025-02-23T11:33:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA187ia82lSDGAQ/+LyAAuMl9ZsFTRzUQKl0cINRGpePXR3hRk37WqjqhfaGx
            fwCBaC/t/akynV308YfgSP4BWD9EdjpGoOFaS8JTIBCID3jn7/BL0BAUYo5InTAk
            DRdFPeUoSdDqFB3PtCnYCwFwEJiUTqc/yC9/y0EUCzoLriJ3iNE32QrnGtL9k0X5
            VbRM+R7a4MrnrUU5itiuaFZ6gdsZbOkeyPV2XfbJkj0+IixnC+/GP19mHTYiMM2f
            OAKh+2gw3u++skUfozMf2nE6mpySCVCCCluQWKau99fvQGmQI35dWS0Vt7bUucSU
            7m5RC3GtILK62U690Px1hwDOVE1hsHxDfnc0EVDnvg+r4VkkKQYS02P5HHbSDQHE
            92mzjiNxG86eEKY02WCYqwZQZxEYClTMcgw9c9KYIFGCzcf5F6mtFlkiMAeA1UM+
            Iqwzm5kZhNtK9Hi8LyDTVrwRcsxzWkKCzMTC4mGiII8J6gvFTHaV3t5j8+Rqwpec
            quure0JicHOprPf4bhjgA9ksty78LWLfr5ZZKG5DVtyCynLEvnEQel3C7inuri2H
            OfzLIArQo0D2sH2PImocgaftfFkTIKi+vFIB8SoJp2wiPB366TGbHYhw6U1Y5Hj0
            l/4y/DvZD2qaGgT585DrvZjlCRYElLM8FEDl0GdckFcsZhbB38N+uP4zC7ITeo3S
            WAG/DmGLrM/Mc5Pec7h+nBslsM8qlvNh4Dmcog35UfRE9/2ahY0Lm+w6sOgja/p/
            Ja51KdQyoISdaiNGt/4LzWI2s+UcLkkTrdaQ6+jPZsOVoECA6WJrXf8=
            =q+1T
            -----END PGP MESSAGE-----
          fp: a32018133c7afbfd05d5b2795f3b89af369520c6
        - created_at: "2025-02-23T11:33:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4NImSg+4iqHAQ//Svr6ZZkAJGg6UpiErPai2njvygvktDVBd9n3MYH2Xg8J
            XILLT4Qrb8pSqzWghjjDigmDJ+ZEyOqUhYHupsDa8HG2O9ZF/OsUhAro1BoLi3Je
            8I566zWHGaMsmZpdKxoeIA0hnpFAuUgZTSxTqpUEaYmx4I4jw4hPdOsDi97knhIb
            Nf5UqylgtY1A+pC4CyQSQpYbObDM5fj9BWuYrjN3YnPrM1Q7vZ5JSQWfxHIa78ZY
            3t1Lsu9/xfMQ9qgcr+b3iT257eKmvl7z6wiNO6zzxwwBw3IcC7dq1VOr6trZoKkJ
            u8TU83x4HHNvRImguN8bXa4lUdMtKlsfdbylud28UA/GHboVXkBPDtYhZgbwJXDz
            LbIiDxpxrHuirZnvd+Vxv2SNBG58ovy6ik5fau4NzgJUHIl8de3meR+S2Z05TDg9
            OvokLqjBu7HnZLCGriQrkvMN5klYE/ryfBKqPik5empY+Mbczz5auHZAFaXStZFx
            B5twr4zDXFqqZ1GMNyFcBlVTG+/uv9FIe/R26nDIFfjf/AwjcMb8LiSeDZSCywoQ
            OFb6cFPhGC5IlJT2U4CXIE4jGGfPv1AZQESvUC7rzu2a2PwtExEwvt+QKqb72Atx
            di3jWxHPKQCZJ92AVwXv+P16ZREeHA8GOm8EVjoGC6IMJPbxSXrArfpoJHI1JPrS
            WAE43Xq+89tx4cCj7AkodhRLEuOrOXVt1rFwk5/JZ664xeymaOs4StCvV4ymJcDC
            1hxh26EHz9O0r1bWBvHyfmaMEfFE6xu2CrfYgBUte9VF0A13+N4HLh0=
            =4xJI
            -----END PGP MESSAGE-----
          fp: 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
        - created_at: "2025-02-23T11:33:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9T+KNkhS2haAQ/6A8vc57/7pHZ4epZBWjgAKONnSG0hrOSznlQz4brEETWE
            0iSdchMXspfgTCag6rlQjfqSscRIYB9o1nHw7u6IsAxko8WwDhylPQMQpKUPxxPn
            OJfkUVom+C1tgGWTAzRJcFq3SnfzpgvK4qH+/yNHQhGVHzRuqpH/JNNtzqSqeyGa
            lvtDU+F0Lyasd2q0Qd0tE2hNypzDounX3E/VvWjGVxbvlRJbPlM2tLWanxH4kjwE
            IMyd/mU6Q350KDcHHfeEeoTlYecndB/wefZXJMSBgw4VXNjK9ARnBi3euWhvq7Sz
            bsIKXe9aAO7L2g1q3ArgUJA/O3aMv/Z5Uo0FjjTd9y+emYMepB3HQrqeGRImRvv/
            GPwaZMqUsfTDMOFjGTkg7YEUIvdWrkMcpKhOjU9N3z4qfXR8ogGpebwQ+CQglZ2z
            Fb7VekI+qovMK53IHBUB4hq+fWgFLHA3VrnmrER6ATAnFgxooyabczaOPAh9w3zd
            jWa4OI+L9zIE/eXAmiUU8vNEiulIhHclDXKMFBzvf3HOSwKDpAktXge/G2zKLRhr
            5Q5wNsT1j6tLPWx8+DqqCEbCGn979m3+aMBIWM2miTlRiG36mWLXVZfWaveEY8+y
            d9cUj1xR2pJ6XrgwkAAeL6yyEAea8AxxK1Mg9TNP32RWRqzK9II+BWwtZbzbmyjS
            WAEgDMYzYW5TfhnOBXeP+ZSkXfZcEYdJzbBMkF2RumANkfXo4EQmnUSKhBu5jxOj
            rOwt/l39dl5oW6wcnhv9lbnLgcJ3vcAkiny2bMhJDUfAFCO43wWMd2w=
            =xi4x
            -----END PGP MESSAGE-----
          fp: 05588f4245256f75a8da42e5d4fe28d9214b685a
    unencrypted_suffix: _unencrypted
    version: 3.8.1
