wg-ataraxia: ENC[AES256_GCM,data:DUXlhmTvB5WIJEP7vgr9+YNHlpC0S9Uhcnrp30fvXRehQdGCJvQeOYfHA9ZQ7zl3ZXFHeeM5YbAP0y3eRfvjY27+poW5jzOpj8nv7PB0JKQsF39nYBvWkFg6YpmNYnF6yOWKOK7Ae2cXE4OCWGhGKEtHywv04Mr9b+GgfpFWVxqvanAJ7RFz4nmGf8KK6cKaCyRCeXonEjXh9DfzstIiMYGtBULruw6AZQZP8dRQxoyFQ0/ICIAhiimD5IF/4l8rrdgHYxhn/vZdkhBOfRsH0X19/PiSWdLKAglvCcZK6u0lWEqFMnJFtY77YxXNwEbo5mFN8OVhK0f5T8WGOx5D0dIrkHTaFaOhltMsKwClla5WiYEld5gVuz9TGKoX/W8YANz38fXl2Z2cPShQRN8poHGkTB8iLvVXLx5G3LKMouw01lB+3nrRqZle/THJjFXFhrGla7gGXrKknRq/A/g2CwExiCJIB9num1duTBveQaxSQQ==,iv:h8m/dXC77L6p46rEYIiklZTDUTZgYBg1yiO/klQJGRg=,tag:uEeDkGpaTalFhPT8+R/X7g==,type:str]
wg-dell: ENC[AES256_GCM,data:IUHBtDHFYIhtsO20RGo4Azv2Pc/dbyBvG8F6UJcdtqLRNnl6Q/C/rUZZytsq5tmDeyZ6EJfA8gcEsMcqYdSWhR9lM7cVf/JFGBS4EA82NT+JiV9PzdTahj0eeGEmWsjMsWh74RNkAsOiI3UWIgq3ICuHY4dgWTWmfOz2Fya3uatFwSCgwdCJKJIFIcH/qEdunTL0Rdcj+yykE3OEOGB3ftZFX9cRFhndZhedJKcUdJsBGMauu7w3dFzEbgOd5hUThxaWTWFxStx4DuGNvUtBC1/i/iWM0tpXc0CpnUB6Y0TRW9JKbu0Noo05aQD7neZEK+cJfNLOS7vAu6XRP+hPlqKQQCbvZJRYVhsgVtpNSaIoFtDoL/8kifoyU2JDxWMH1XaqmpWDe3QnpCfh4rAyRRqxP+NdSpBr+Mk5QgTk+zVFhuVFUU38hkbHbIC3uelvYUSNbz7oGOfO1cqBDWlVVJgCg5viiiXodb8NxJVlX/ar32FXq3k52Aajd1NzdFwaWzlUVDEX2OQalf1HpQCdEqRb39NteCtQOii4KCbjod1rT7++H0xProk3L5DyRFeePpjTwbuTqMo0Bg4f5bZ0V484ZoU7Wzho//BrcWw1paKf5rcaVNPZ5grWWCpbrOqc/UVxn0ffi81UpM4c7/rqHj/r60qoWEnvwLWiKFBEd/aJJDZtbp8HH0HS2q7NyXD4X3PHi1CsZoPg3LKbLOxDyUXxihruEhwGe+CYuwFeh2pT7fDhe3AtWw16ThfikjYV/T9PcpHJF4iLupNTKESAbjgges1x2wWVXtqIvPaIe/es9sBEawHKyAJenxoKDu3zLw/efcwQe+PRrzzTlziRjwA8lxl0+Bxf+qx7rrY7eWr4WOjtsbImThJiAagHNRqbtjtCNrm7OsSD4Uob8JlOhpO4F/HSDJDkoncOY/BBVNphOz1xDznJSRLYAavxIcdNnGIBjDIK6pGNFpK1jTqmSVf1W0o2lBnTPrZrbX0nrgAvVJaIdnubrlv/33fAPpvTJF3ymFIVngDBoODXLXcom7OhAEAWAteWQj1V+Xy0xj80QFgWLL6crt2t5qfY6BEbeWvx0mAhFqiwe6sg3CIyQuicdswCRE1Qmq9JPI0MB3Qg92Jbg10rkXx0lXuNptDI9/BrU141NTTuh4FvGF4spqCbpZQd2JAcICauQ2+XBWFwQDdMz57Bqzwc3kPKCCcuf6Yj3ZGt/bcVNV1gsTeyCOzjEVR86a9BL/wOd10niZDh8xfkqEjZ3r8U56+9dlaKrQ3tx2bOX3AAWL0S1D/j9flY5tNX3WaJz/b6aPE3UcK92IcfJzhbYr7pm+NwndSQqdoCcl1QnLPOCcEjnPbkWaw6lORu8LBFnnmGEBPBfikth6uMUW91ZVR8A5qU8xSplUqAVN+cDil5RjyTanrL3tMw+8AHHa/ifYViQJyrxZ7+iEOYrsRf8AFgqVnaDlWfM15knjPYozgjR6C+JqRdDgqHVkZwrrbPSVoCOq2Yf98mR5qVUFwi9BTQOnebPG+H0Yr3jYkdRB7AuN2BKYhvc9NDsznI9rXkQdSTliCmZgPO/TyCGUN8vXvjlXcyh8uIix+vYbhf4yWBIagCf+OvaoOO3NHs0YADNm37dun8x8UHKUcmRXDLvz68oRFNG+SSbPsKZNplCO8Jg2oSwkghrgIfvhfAv8eqNBQ7bGkYqIXVz2PCenVRpXVIYN2TQPt+LjRqaNVfNujeNPDGBBSQ0FM1NmdAHy1dMtuVEZzX2Rmxn5dRO0IK7NwogNIgVC7Jw/mCT+CT9SHhZKpJaHdGOv4O513rFG29Qeyoi6szP5dNNrhOUHGTJZHFLqBtAlTneevR2vnoenVzmr8+xkvJq0wd5UHxoMlNKnF5ex416D2kBpiYBLZP47FUDkfbsYlx+vQbaeiEgT/V4Q4YmZ5h67AoidLISKaFg2dWyeJ2gmmUFON+mPiJmJzoDLCOZimi7GdNk4pjX2qY29pAm7jQdF7j3ZpgyGt/nElRrIEEhek813M2bt25murpEEbgoJf5tR44qgpbdTycdz/G3YLIQ3sgY0RdEm9lkolCO7Pqh4TxSw4WzbSiMUg49cs4z0b62mCBQSr5smTNv0N4+QAsJ8PnCZEgVm0buU12SLtY6Ty7/RWB8Gqb0I5SHUzOvkGEuME4FG9yMiJ7UT+NhdV8Pq4C3TgFeSqDnH0qIkjOgZng4Rl1TEfZvnLq1bjsQIAPl4nfD3RY2+VV,iv:RhPtay1IjAq40plSm5xVzUGbdkCcLwCVsOVysChDGag=,tag:ML99P2YlxsNIdmcxu6hbKw==,type:str]
wg-hypervisor-dns: ENC[AES256_GCM,data:bqiFalZaSx1Xguhufa656uHfyfcCdeXJdtcsWeaGMwBJwO7JXAnFw2eB8y2H4Xr1nrwwravnp3hPmEcLI8eIWUCU+IhNDF0ghkU+YtBcb5HWNRLV9lqqs9dGwEcX9SXQ12lTci0uJxo0nMWcNQWTSALjx7GLHQLmSbmRrGFl5Fxc+NjuAnEH6bQflOVQhjqaUwgYYTOnxdIF6ljDg2+28pfM7RixxKsJc9E7iO9JHYzzwL2Q63w103fIlfroBQ0t6S7gqqB5ahXB/gnr4Cgq4gMFdLdL7LCKPEmpT442wvLt4yjNytdC3P+jxjOK4AHpFHQUps+MH8eapkIrTUhnveITi0dgxOVyAIls+wDYphHEYxXUkkSw+BlCvbygSfHfwj9Lxksn7k1E9D0EN68yNtFpR+72Bfl6H/7BOw==,iv:3GcVUj9EzogzQ78ImEkBfT1Ula28i3dKH2be5Q3ignA=,tag:9+54I6P/JKtmqW5RyOLTLw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - pgp:
            - created_at: "2024-10-20T23:10:46Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQEMAwcagTG/Fm6AAQgAl7iMKm5A6tlff7APh/7WNsV1MmHvPJ5v4w+joONn7+So
                ZDFcnpkVUdaQ5RHcK+A4epd/nDQuhDLkKV5bWJZxNpZjNFIKyZTB7VYCUfNdE8lN
                MbpuJ5X5l8Nl7PiR+e2JW+W7xBi1Rgre+hACUZsXQs/KGTMQi+3OxD6nQ7Bb2Ddt
                mk105pRNwMzUYoy13J+eQsC/yvHPWb548ogrlYPZ11dFCgw2coRb2BxtIx4ouly9
                Tn3UqwpwPyZpK6uK9Xqtt2nZaTroZPYO+E3zXnsYrGWWDyzidRcIFqD9qhdWtWHM
                oyjNZo8KMwAFws7xXi51Q6ZZZn7iCMWWofrtS6B2ytJZAQCICWzRLt2xkx5RNDlv
                t+b7zYhtbpvSkpNYxY/gHOf84ZpJyBSwAAmicC18nwKDeULGBtXbqVVHIl2O7cY/
                1CTBhUR2VtsdidYzPkjC7DdEd+ZOP0LQjuI=
                =fvXk
                -----END PGP MESSAGE-----
              fp: ad382d058c964607b7bbf01b071a8131bf166e80
            - created_at: "2024-10-20T23:10:46Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA7DEqu/04FqmARAAnp8692hWBe+bJC5Ely+Ki18lk00kO4DGADuy8+EQe84W
                //bDaBaST4sDe8NEs4cvCDY0wvAvZD1QbC465LoNbMu9BI3cMfaJKJ3H2tPla4mM
                vtckGKe8oM/rsmFSNSWwinDAxb73FkkORMCVx8TbdqRF4EzO7FaWZHSFoeiamPeZ
                1cgKrJs2tlS4COsTQ9QPApyT69ih3WOaXMG0Un4btgFiuI0+rlTzpCcX3mYDagDj
                l/wsH2q0Wq5XGJzNqEdkHugYAcRLtIm/+nbarqdvfEK4mvKnIgarvrW/RZHWGa1o
                hV2VrbSvM4D/vY/API7sIfvUOXF2J3slu5h1RnHZ3yTMHTsYxN/GmNK+HZqADcwb
                x3apRqov1VF9HrIxRnH248XEEIheX2k62slIoAdzwN5y8SIvfWcwqNOjAWzMcegL
                BNLDFa0XZYr46WaokZsqXJUqWkvZkkaTTVNWiOQ/sjzHzun5DzkeLq55Kv98FOu9
                o8Cf4PIy0/eRlH81e3sACK2+NwTwU3YBFIOZLw8zRlsqv6ONTZUrsQhIgziE7PF6
                hfgaKhJULRFJNwSVKUTF4SS2x+6Vxzn9X8vPGmwPVBOk/9TzCEBviTlK0HM76dsb
                bVEsrSD0FzZETzwDe3l3qhzaA3YT2cKdbk9CofCsGdIuQzlfCyDPmrKyIj0eR9rS
                WQFb3UqjRe0XFQmHo6sZefDFIw5UUWz8vxZKo1pCIQrd2MogiRYSYn2C1LTgWOLY
                hkTMCBikIr8Y846gZACcWVivPqYvnPe7x70zNRCLnNv0t6tGfjc7Dg2i
                =Jpn0
                -----END PGP MESSAGE-----
              fp: 4ec141b4dd5a00e108b36211b0c4aaeff4e05aa6
            - created_at: "2024-10-20T23:10:46Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA187ia82lSDGAQ//TMP698egTlcg9EIEu70Ij4GraE7JcEKF4lPWWLW91tq7
                oxCqdaQ5lLTKIc1lhoxymwNgJV+BGEn8chnIwFbo/T0nBvKUrnOd0dhGA/VI+4GS
                N5VzGeBXbBbxLCjXRJZ7fi35YArLKrxdupd4sIFr7oQjim++MiB6BuDFZuT4jL+j
                PJuh8ScpwbotZYM+f2PQLGahWP42leELPzapA12v0bhYiOigwPDyzTS3q+eMIT7H
                Z1bPtn7LQcIkm51RDn5Nm0WsDcvq/ws4SPweU9TsZjCJisemR6S7IZnJWZuyRNvE
                t5lN749oMZ2idvHetD2pt/HVIIi64WMm5HFOE+OUpBU2DIBGdde7rjFbSNJoKFPf
                NA7hqVclMU3upyOOWESfwMEINjgkn/WJrwjkhielvRzUsLEhdF2eZavTYpAjJwiX
                mBs4UDXisJY8Nhb9gCgY0e5nIQa459t1+x3cmEkrUwgVxDYVIauT9rCRKcpdQqpu
                s3n0rPhkMzqoNwnoZH6qwCAeeLI4gR6ac2TH/sqRwfStCkffxRVQpNqecWiqoiS1
                pyQ3ail6riHZsAy2StzhuToKAl8JOM4aHkcjbZ+VX13DyvAlE5TqUmfV11emGQoD
                dclLL4PLmy89zcWe1uB0n91FokQ3F7q4p3tt6oYU6OEC+KpPw5HkDnAPwQLExZvS
                WQFDVVz4c63wHOeF50oDEOQRYR+AvBh2RLo37sxAksJGGFY7XTS1Bt6L279/p4SE
                7EefUqAxOV1oyxCvHgr1H3+9LKsdqsSvXMsfx33Phth2VJQLu4bJeqvl
                =d6cn
                -----END PGP MESSAGE-----
              fp: a32018133c7afbfd05d5b2795f3b89af369520c6
            - created_at: "2024-10-20T23:10:46Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA4NImSg+4iqHARAAzFLwzQyCqSCmoCOxwMxkONSYreI6F5ztP1f4uoEtatL1
                7tlxc4iZBsBlG/wKOW4sXt+H+PLiKgiLdpl4KWDl7bxMJDTCUjt6HP60vGDKiKIo
                cYwZIYCdpRhDNaI9YgJu25fRlLoamMpSN7ORdjhciaY5SpQ1SCEB6hq2ihfnJNDP
                NrKgsak0uDUIyuJeoqcdUkVzs2RdF1gp4lv5RYnsEPN3yjmwNB10/yJkoCoho1Tm
                hWVuIwp6j3fuGV7VqvHlCtC5BV9tdJbW9Nqpm3ZRizNok/hT4QamfHkal6swunid
                HVmoSNJysqNaKV5sRAxKTkOfwTH2nHTbh9GOHmOO4Xbl2k2ide7FLty2VN+Q/tMP
                lTposGKMXsYuSa8X8En8eVVmXi3GhJKWqkxKdj6cwiimAAo3ZGuzCWuGzkL+xhkt
                Z7JxvW+3CoZwNJTfwJGF7oHMX+0lDzgJiCWGJ2zNQ00rblx9uQm4o7ZrbMpex5Of
                jWdBs52teovSKZtedUjRvM6a4J4MiIxIieJ0A+NhNwx4MAHI+hqcS5XorruSDsQB
                ZIBKyKAim1WJB16HEXRP1gDoqeUtqyLQtKu/57PZt8gJ/V1HV6qrrlfiT/iWkTuY
                zeuwsq8/k4tl/D1Jig68C1OSrWi1dhD6XG6wboZwnH67PG8n+lUg7X94eYyQuGzS
                WQH5PORfSUtfzHYDRuVVgCgePanQ+tsTIm+xY6Asbapcqe+QY9N3slU/+VrFRZjK
                qBfWHgZypXjDypuncfBmgXNfrgiy7XXLnGn36hjIqkqtmCLxJZyDAdat
                =t9mJ
                -----END PGP MESSAGE-----
              fp: 78fa8fb95e85b2b89f1dd4f0834899283ee22a87
            - created_at: "2024-10-20T23:10:46Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA9T+KNkhS2haAQ//e1EZIJh9aOrSN6jLnDJ+I3mrp4V+R4iIgH0tvPdJ3AdD
                Fo96D5Zb52D7tIC1E3XKp+sPH2gnf1tEKd6V0sZtT7iXw1ulHd77uANNfWjPWVvM
                UcDA1SGzSFtJYneK05dEWs3s+3SY3ntvnBc5EcTsyhP4meofoYqSuw6e3ifauVTT
                KYqb3UvOH0tXR8X3ovd4SpTtL48GVaTMJhtqekU8zqpbm1nhMl9yyww8Mj+Daf2+
                lw1XFPlCnz193bxU6sZJ82d5NrP+1AxdoR+NKyorEXYItajFiNYJ7EI9DTRkbRaM
                Rr6VAzBnCOBhntoWG1zvrmK6f+ZaPBr6aYIdZrOCMVX3kpZuSmjgnNoH88ruYAGy
                8e2IkjRq2plWXFW8D1F5qz5KYRendknNuMSijdh/xqKvgE7/rZlM0J4SYaM5hvDO
                x8lNq25InjVoMi3vcpMVY2GcppR+JLd4g9FNjqqXzD3UG6VH4chgX2Is4WqeoBd7
                3Y7KuPmTvS9VB0zIPAoxNNLKIPWtG8OvrUdXw6SeCOBdvOzRqIq9mECLWhXrQXed
                bDWhSMFwWG/duYyM10WGwBjYkw5irmJMSTXvAn9E3bh34raJRYziT83hiayqAyiH
                uWeshQR1mfqfWCSu/ttWJissLkXmIsW2YceyaYQG+IcOR4dmliuNlkFv1aKTPLXS
                WQHD/Gy+VvqyRmRaVG9r/wcs+McPxhApd/+Kv+ftlERXZsSvpkZjdA5PqPjRZiKF
                145jYn7Gk+InbcBBtM2BTz8whkpujfpiUrITffX4Ejudt05m/KebV7Bi
                =8hXP
                -----END PGP MESSAGE-----
              fp: 05588f4245256f75a8da42e5d4fe28d9214b685a
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1n0prg9vynuwc56gn0xfe5qde8wqcd4uzg5ghhhetu2024ckvjyvqxf49el
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ekMwYnluRVo5OWd3dUNP
                UmovaFZYNldDQnJsdzVZcjFZS1FoWVQwcms4ClpseUdLNVRtTjBuZ2hUVlNUUUNm
                VGRqRWVkN0dtZStHRjFmOUJiczJEckEKLS0tIEhoOW9pQld2a2pGVmsvTjJ0QUxG
                WnpEekoyYXg5N2p3VjJFVXgrcVJDZ2sKVrJO99hgHIKaonmN7aAxz2AR5rxASiiQ
                4Cjx+HpdWfrmk6k1x8uQ8KOjJcvYHOVfG6tuIYCye5IzBOxo7s2ydGk=
                -----END AGE ENCRYPTED FILE-----
            - recipient: age1ztrteyc2hae7c0tlrjx9pcjjtyeqazsq7ztf7dcmxlyxg5x2mcwq75p65f
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRnBOVFpMVlZFZ04wY3E2
                SDduSHhRMC82WkpyR0VIWVlwdWdDQytOSERzCllqRS8rQlFhSUl6MnhoeFRidnVW
                eUhJOSs4YlhZL29raUVqMjJUTUd4YWsKLS0tIHlaaUlVYnMwTW1DTjRDQVJta3Ar
                Rm5jbWdGVTAzZ3U1WUFoV1lKTzhnQ0kK8fPRjAM214R+ffghmbHFd7t+VbiaEIbQ
                nmhBo38fNMc3KyRcdfmTUi2D8jAKqhhL34moLR8jh21io4/Sep8JLIA=
                -----END AGE ENCRYPTED FILE-----
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-21T16:36:51Z"
    mac: ENC[AES256_GCM,data:AmoEIOX4ROFpg60hymSw24oWXs/SodzEvodq7YkUkbeD30woka625KmEwTbpLH6vqaODJU8NS5ioHaFg+ErFY84B+FDz885UYOjeNK0Z/dm4AqjBi3YDxKmfedwpIfzpDO+hDHGOP3/EBALO2Se87Q9hu6NwED+nSRqLqlpPE9w=,iv:tzt2hNr28mSDhTwKBuPVIMhGiD0/KlE/oSx8HICH+Is=,tag:qh29t54uCGxt8flcj43cPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
